# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotOptions.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotOptions(object):
    def setupUi(self, PlotOptions):
        PlotOptions.setObjectName("PlotOptions")
        PlotOptions.resize(645, 438)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        PlotOptions.setFont(font)
        self.ColorHisto = QtWidgets.QPushButton(PlotOptions)
        self.ColorHisto.setGeometry(QtCore.QRect(490, 140, 110, 32))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.ColorHisto.setFont(font)
        self.ColorHisto.setObjectName("ColorHisto")
        self.lineEditAlpha = QtWidgets.QLineEdit(PlotOptions)
        self.lineEditAlpha.setGeometry(QtCore.QRect(90, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.lineEditAlpha.setFont(font)
        self.lineEditAlpha.setObjectName("lineEditAlpha")
        self.lineEditBins = QtWidgets.QLineEdit(PlotOptions)
        self.lineEditBins.setGeometry(QtCore.QRect(90, 150, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.lineEditBins.setFont(font)
        self.lineEditBins.setObjectName("lineEditBins")
        self.label = QtWidgets.QLabel(PlotOptions)
        self.label.setGeometry(QtCore.QRect(40, 100, 56, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PlotOptions)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(PlotOptions)
        self.label_4.setGeometry(QtCore.QRect(420, 250, 91, 51))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.radioButtonBar = QtWidgets.QRadioButton(PlotOptions)
        self.radioButtonBar.setGeometry(QtCore.QRect(520, 200, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.radioButtonBar.setFont(font)
        self.radioButtonBar.setChecked(True)
        self.radioButtonBar.setObjectName("radioButtonBar")
        self.radioButtonBarstacked = QtWidgets.QRadioButton(PlotOptions)
        self.radioButtonBarstacked.setGeometry(QtCore.QRect(520, 240, 97, 18))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.radioButtonBarstacked.setFont(font)
        self.radioButtonBarstacked.setObjectName("radioButtonBarstacked")
        self.radioButtonStep = QtWidgets.QRadioButton(PlotOptions)
        self.radioButtonStep.setGeometry(QtCore.QRect(520, 280, 61, 18))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.radioButtonStep.setFont(font)
        self.radioButtonStep.setObjectName("radioButtonStep")
        self.radioButtonStepfilled = QtWidgets.QRadioButton(PlotOptions)
        self.radioButtonStepfilled.setGeometry(QtCore.QRect(520, 320, 97, 18))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.radioButtonStepfilled.setFont(font)
        self.radioButtonStepfilled.setObjectName("radioButtonStepfilled")
        self.label_5 = QtWidgets.QLabel(PlotOptions)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 56, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(PlotOptions)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 61, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(PlotOptions)
        self.label_7.setGeometry(QtCore.QRect(30, 400, 56, 13))
        self.label_7.setObjectName("label_7")
        self.plainTextEdit_Title = QtWidgets.QPlainTextEdit(PlotOptions)
        self.plainTextEdit_Title.setGeometry(QtCore.QRect(90, 310, 201, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.plainTextEdit_Title.setFont(font)
        self.plainTextEdit_Title.setObjectName("plainTextEdit_Title")
        self.plainTextEdit_xlabel = QtWidgets.QPlainTextEdit(PlotOptions)
        self.plainTextEdit_xlabel.setGeometry(QtCore.QRect(90, 350, 201, 25))
        self.plainTextEdit_xlabel.setObjectName("plainTextEdit_xlabel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(PlotOptions)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 390, 201, 25))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.checkBoxNormed = QtWidgets.QCheckBox(PlotOptions)
        self.checkBoxNormed.setGeometry(QtCore.QRect(20, 200, 85, 18))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.checkBoxNormed.setFont(font)
        self.checkBoxNormed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxNormed.setChecked(True)
        self.checkBoxNormed.setObjectName("checkBoxNormed")
        self.checkBoxGrid = QtWidgets.QCheckBox(PlotOptions)
        self.checkBoxGrid.setGeometry(QtCore.QRect(50, 240, 51, 20))
        self.checkBoxGrid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxGrid.setChecked(True)
        self.checkBoxGrid.setObjectName("checkBoxGrid")
        self.checkBoxCumulative = QtWidgets.QCheckBox(PlotOptions)
        self.checkBoxCumulative.setGeometry(QtCore.QRect(160, 200, 101, 18))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.checkBoxCumulative.setFont(font)
        self.checkBoxCumulative.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxCumulative.setObjectName("checkBoxCumulative")
        self.pushButtonOkPlot = QtWidgets.QPushButton(PlotOptions)
        self.pushButtonOkPlot.setGeometry(QtCore.QRect(500, 390, 110, 32))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        self.pushButtonOkPlot.setFont(font)
        self.pushButtonOkPlot.setObjectName("pushButtonOkPlot")
        self.LabelPlotOptions = QtWidgets.QLabel(PlotOptions)
        self.LabelPlotOptions.setGeometry(QtCore.QRect(190, 10, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(24)
        self.LabelPlotOptions.setFont(font)
        self.LabelPlotOptions.setObjectName("LabelPlotOptions")

        self.retranslateUi(PlotOptions)
        QtCore.QMetaObject.connectSlotsByName(PlotOptions)

    def retranslateUi(self, PlotOptions):
        _translate = QtCore.QCoreApplication.translate
        PlotOptions.setWindowTitle(_translate("PlotOptions", "Form"))
        self.ColorHisto.setText(_translate("PlotOptions", "Color"))
        self.label.setText(_translate("PlotOptions", "Alpha"))
        self.label_2.setText(_translate("PlotOptions", "Bins"))
        self.label_4.setText(_translate("PlotOptions", "<html><head/><body><p><span style=\" font-size:16pt;\">Histogram </span></p><p><span style=\" font-size:16pt;\">Type</span></p></body></html>"))
        self.radioButtonBar.setText(_translate("PlotOptions", "Bar"))
        self.radioButtonBarstacked.setText(_translate("PlotOptions", "barstacked"))
        self.radioButtonStep.setText(_translate("PlotOptions", "step"))
        self.radioButtonStepfilled.setText(_translate("PlotOptions", "stepfilled"))
        self.label_5.setText(_translate("PlotOptions", "Title:"))
        self.label_6.setText(_translate("PlotOptions", "X label:"))
        self.label_7.setText(_translate("PlotOptions", "Y label:"))
        self.plainTextEdit_Title.setPlainText(_translate("PlotOptions", "Histogram"))
        self.plainTextEdit.setPlainText(_translate("PlotOptions", "Frequency"))
        self.checkBoxNormed.setText(_translate("PlotOptions", "Normed"))
        self.checkBoxGrid.setText(_translate("PlotOptions", "Grid"))
        self.checkBoxCumulative.setText(_translate("PlotOptions", "Cumulative"))
        self.pushButtonOkPlot.setText(_translate("PlotOptions", "OK"))
        self.LabelPlotOptions.setText(_translate("PlotOptions", "<html><head/><body><p align=\"center\">Histogram Plot Options</p></body></html>"))

