# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotOptions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlotOptions(object):
    def setupUi(self, PlotOptions):
        PlotOptions.setObjectName(_fromUtf8("PlotOptions"))
        PlotOptions.resize(645, 438)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        PlotOptions.setFont(font)
        self.ColorHisto = QtGui.QPushButton(PlotOptions)
        self.ColorHisto.setGeometry(QtCore.QRect(490, 140, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.ColorHisto.setFont(font)
        self.ColorHisto.setObjectName(_fromUtf8("ColorHisto"))
        self.lineEditAlpha = QtGui.QLineEdit(PlotOptions)
        self.lineEditAlpha.setGeometry(QtCore.QRect(90, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.lineEditAlpha.setFont(font)
        self.lineEditAlpha.setObjectName(_fromUtf8("lineEditAlpha"))
        self.lineEditBins = QtGui.QLineEdit(PlotOptions)
        self.lineEditBins.setGeometry(QtCore.QRect(90, 150, 113, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.lineEditBins.setFont(font)
        self.lineEditBins.setObjectName(_fromUtf8("lineEditBins"))
        self.label = QtGui.QLabel(PlotOptions)
        self.label.setGeometry(QtCore.QRect(40, 100, 56, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(PlotOptions)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 31, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(PlotOptions)
        self.label_4.setGeometry(QtCore.QRect(420, 250, 91, 51))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioButtonBar = QtGui.QRadioButton(PlotOptions)
        self.radioButtonBar.setGeometry(QtCore.QRect(520, 200, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.radioButtonBar.setFont(font)
        self.radioButtonBar.setChecked(True)
        self.radioButtonBar.setObjectName(_fromUtf8("radioButtonBar"))
        self.radioButtonBarstacked = QtGui.QRadioButton(PlotOptions)
        self.radioButtonBarstacked.setGeometry(QtCore.QRect(520, 240, 97, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.radioButtonBarstacked.setFont(font)
        self.radioButtonBarstacked.setObjectName(_fromUtf8("radioButtonBarstacked"))
        self.radioButtonStep = QtGui.QRadioButton(PlotOptions)
        self.radioButtonStep.setGeometry(QtCore.QRect(520, 280, 61, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.radioButtonStep.setFont(font)
        self.radioButtonStep.setObjectName(_fromUtf8("radioButtonStep"))
        self.radioButtonStepfilled = QtGui.QRadioButton(PlotOptions)
        self.radioButtonStepfilled.setGeometry(QtCore.QRect(520, 320, 97, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.radioButtonStepfilled.setFont(font)
        self.radioButtonStepfilled.setObjectName(_fromUtf8("radioButtonStepfilled"))
        self.label_5 = QtGui.QLabel(PlotOptions)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 56, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(PlotOptions)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 61, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(PlotOptions)
        self.label_7.setGeometry(QtCore.QRect(30, 400, 56, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.plainTextEdit_Title = QtGui.QPlainTextEdit(PlotOptions)
        self.plainTextEdit_Title.setGeometry(QtCore.QRect(90, 310, 201, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.plainTextEdit_Title.setFont(font)
        self.plainTextEdit_Title.setObjectName(_fromUtf8("plainTextEdit_Title"))
        self.plainTextEdit_xlabel = QtGui.QPlainTextEdit(PlotOptions)
        self.plainTextEdit_xlabel.setGeometry(QtCore.QRect(90, 350, 201, 25))
        self.plainTextEdit_xlabel.setObjectName(_fromUtf8("plainTextEdit_xlabel"))
        self.plainTextEdit = QtGui.QPlainTextEdit(PlotOptions)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 390, 201, 25))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.checkBoxNormed = QtGui.QCheckBox(PlotOptions)
        self.checkBoxNormed.setGeometry(QtCore.QRect(20, 200, 85, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.checkBoxNormed.setFont(font)
        self.checkBoxNormed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxNormed.setChecked(True)
        self.checkBoxNormed.setObjectName(_fromUtf8("checkBoxNormed"))
        self.checkBoxGrid = QtGui.QCheckBox(PlotOptions)
        self.checkBoxGrid.setGeometry(QtCore.QRect(50, 240, 51, 20))
        self.checkBoxGrid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxGrid.setChecked(True)
        self.checkBoxGrid.setObjectName(_fromUtf8("checkBoxGrid"))
        self.checkBoxCumulative = QtGui.QCheckBox(PlotOptions)
        self.checkBoxCumulative.setGeometry(QtCore.QRect(160, 200, 101, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.checkBoxCumulative.setFont(font)
        self.checkBoxCumulative.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxCumulative.setObjectName(_fromUtf8("checkBoxCumulative"))
        self.pushButtonOkPlot = QtGui.QPushButton(PlotOptions)
        self.pushButtonOkPlot.setGeometry(QtCore.QRect(500, 390, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        self.pushButtonOkPlot.setFont(font)
        self.pushButtonOkPlot.setObjectName(_fromUtf8("pushButtonOkPlot"))
        self.LabelPlotOptions = QtGui.QLabel(PlotOptions)
        self.LabelPlotOptions.setGeometry(QtCore.QRect(190, 10, 281, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(24)
        self.LabelPlotOptions.setFont(font)
        self.LabelPlotOptions.setObjectName(_fromUtf8("LabelPlotOptions"))

        self.retranslateUi(PlotOptions)
        QtCore.QMetaObject.connectSlotsByName(PlotOptions)

    def retranslateUi(self, PlotOptions):
        PlotOptions.setWindowTitle(_translate("PlotOptions", "Form", None))
        self.ColorHisto.setText(_translate("PlotOptions", "Color", None))
        self.label.setText(_translate("PlotOptions", "Alpha", None))
        self.label_2.setText(_translate("PlotOptions", "Bins", None))
        self.label_4.setText(_translate("PlotOptions", "<html><head/><body><p><span style=\" font-size:16pt;\">Histogram </span></p><p><span style=\" font-size:16pt;\">Type</span></p></body></html>", None))
        self.radioButtonBar.setText(_translate("PlotOptions", "Bar", None))
        self.radioButtonBarstacked.setText(_translate("PlotOptions", "barstacked", None))
        self.radioButtonStep.setText(_translate("PlotOptions", "step", None))
        self.radioButtonStepfilled.setText(_translate("PlotOptions", "stepfilled", None))
        self.label_5.setText(_translate("PlotOptions", "Title:", None))
        self.label_6.setText(_translate("PlotOptions", "X label:", None))
        self.label_7.setText(_translate("PlotOptions", "Y label:", None))
        self.plainTextEdit_Title.setPlainText(_translate("PlotOptions", "Histogram", None))
        self.plainTextEdit.setPlainText(_translate("PlotOptions", "Frequency", None))
        self.checkBoxNormed.setText(_translate("PlotOptions", "Normed", None))
        self.checkBoxGrid.setText(_translate("PlotOptions", "Grid", None))
        self.checkBoxCumulative.setText(_translate("PlotOptions", "Cumulative", None))
        self.pushButtonOkPlot.setText(_translate("PlotOptions", "OK", None))
        self.LabelPlotOptions.setText(_translate("PlotOptions", "<html><head/><body><p align=\"center\">Histogram Plot Options</p></body></html>", None))

