# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vector_Velocities_with_Sunpy.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlowsMainWindow(object):
    def setupUi(self, FlowsMainWindow):
        FlowsMainWindow.setObjectName(_fromUtf8("FlowsMainWindow"))
        FlowsMainWindow.resize(1421, 814)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlowsMainWindow.sizePolicy().hasHeightForWidth())
        FlowsMainWindow.setSizePolicy(sizePolicy)
        FlowsMainWindow.setIconSize(QtCore.QSize(1, 1))
        FlowsMainWindow.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(FlowsMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1120, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1420, 846))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 301, 591))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Infotab = QtGui.QWidget()
        self.Infotab.setObjectName(_fromUtf8("Infotab"))
        self.layoutWidget = QtGui.QWidget(self.Infotab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 291, 531))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widget = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_8.addWidget(self.widget)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.contextlabel = QtGui.QLabel(self.layoutWidget)
        self.contextlabel.setObjectName(_fromUtf8("contextlabel"))
        self.horizontalLayout_15.addWidget(self.contextlabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.InfoplainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoplainTextEdit.sizePolicy().hasHeightForWidth())
        self.InfoplainTextEdit.setSizePolicy(sizePolicy)
        self.InfoplainTextEdit.setReadOnly(True)
        self.InfoplainTextEdit.setObjectName(_fromUtf8("InfoplainTextEdit"))
        self.verticalLayout_8.addWidget(self.InfoplainTextEdit)
        self.tabWidget.addTab(self.Infotab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.HeadertableWidget = QtGui.QTableWidget(self.tab_2)
        self.HeadertableWidget.setGeometry(QtCore.QRect(0, 0, 291, 591))
        self.HeadertableWidget.setObjectName(_fromUtf8("HeadertableWidget"))
        self.HeadertableWidget.setColumnCount(0)
        self.HeadertableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.ImagetabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.ImagetabWidget_2.setGeometry(QtCore.QRect(320, 10, 711, 671))
        self.ImagetabWidget_2.setObjectName(_fromUtf8("ImagetabWidget_2"))
        self.image = QtGui.QWidget()
        self.image.setObjectName(_fromUtf8("image"))
        self.layoutWidget1 = QtGui.QWidget(self.image)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 701, 631))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ToolBar_widget_3 = QtGui.QWidget(self.layoutWidget1)
        self.ToolBar_widget_3.setObjectName(_fromUtf8("ToolBar_widget_3"))
        self.MeanImage_widget_3 = QtGui.QWidget(self.ToolBar_widget_3)
        self.MeanImage_widget_3.setGeometry(QtCore.QRect(0, 0, 691, 601))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MeanImage_widget_3.sizePolicy().hasHeightForWidth())
        self.MeanImage_widget_3.setSizePolicy(sizePolicy)
        self.MeanImage_widget_3.setObjectName(_fromUtf8("MeanImage_widget_3"))
        self.verticalLayout_7.addWidget(self.ToolBar_widget_3)
        self.ImagetabWidget_2.addTab(self.image, _fromUtf8(""))
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(640, 700, 253, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.axes_label_8 = QtGui.QLabel(self.layoutWidget2)
        self.axes_label_8.setObjectName(_fromUtf8("axes_label_8"))
        self.horizontalLayout_8.addWidget(self.axes_label_8)
        self.arcradioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.arcradioButton.setChecked(True)
        self.arcradioButton.setObjectName(_fromUtf8("arcradioButton"))
        self.horizontalLayout_8.addWidget(self.arcradioButton)
        self.meter_radioButton_2 = QtGui.QRadioButton(self.layoutWidget2)
        self.meter_radioButton_2.setChecked(False)
        self.meter_radioButton_2.setObjectName(_fromUtf8("meter_radioButton_2"))
        self.horizontalLayout_8.addWidget(self.meter_radioButton_2)
        self.RestorepushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.RestorepushButton_2.setGeometry(QtCore.QRect(920, 700, 85, 26))
        self.RestorepushButton_2.setObjectName(_fromUtf8("RestorepushButton_2"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 280, 21, 81))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1030, 270, 21, 81))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.Message = QtGui.QLabel(self.centralwidget)
        self.Message.setGeometry(QtCore.QRect(1065, 330, 331, 121))
        self.Message.setObjectName(_fromUtf8("Message"))
        self.MDToolstabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.MDToolstabWidget_2.setGeometry(QtCore.QRect(1040, 10, 371, 771))
        self.MDToolstabWidget_2.setTabsClosable(False)
        self.MDToolstabWidget_2.setMovable(False)
        self.MDToolstabWidget_2.setObjectName(_fromUtf8("MDToolstabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.Intruc_flowlabel_2 = QtGui.QLabel(self.tab_3)
        self.Intruc_flowlabel_2.setGeometry(QtCore.QRect(100, 0, 81, 21))
        self.Intruc_flowlabel_2.setObjectName(_fromUtf8("Intruc_flowlabel_2"))
        self.Instru1plainTextEdit = QtGui.QPlainTextEdit(self.tab_3)
        self.Instru1plainTextEdit.setGeometry(QtCore.QRect(20, 20, 321, 41))
        self.Instru1plainTextEdit.setReadOnly(True)
        self.Instru1plainTextEdit.setObjectName(_fromUtf8("Instru1plainTextEdit"))
        self.Options_CalcgroupBox = QtGui.QGroupBox(self.tab_3)
        self.Options_CalcgroupBox.setGeometry(QtCore.QRect(10, 70, 341, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setUnderline(False)
        self.Options_CalcgroupBox.setFont(font)
        self.Options_CalcgroupBox.setObjectName(_fromUtf8("Options_CalcgroupBox"))
        self.labelTitle = QtGui.QLabel(self.Options_CalcgroupBox)
        self.labelTitle.setGeometry(QtCore.QRect(100, 130, 131, 31))
        self.labelTitle.setObjectName(_fromUtf8("labelTitle"))
        self.layoutWidget3 = QtGui.QWidget(self.Options_CalcgroupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 20, 218, 111))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.FWHM1_2 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWHM1_2.sizePolicy().hasHeightForWidth())
        self.FWHM1_2.setSizePolicy(sizePolicy)
        self.FWHM1_2.setObjectName(_fromUtf8("FWHM1_2"))
        self.horizontalLayout.addWidget(self.FWHM1_2)
        self.FWHMSelector = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.FWHMSelector.setProperty("value", 3.0)
        self.FWHMSelector.setObjectName(_fromUtf8("FWHMSelector"))
        self.horizontalLayout.addWidget(self.FWHMSelector)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Pixelsize = QtGui.QHBoxLayout()
        self.Pixelsize.setObjectName(_fromUtf8("Pixelsize"))
        self.Pixelsize_2 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pixelsize_2.sizePolicy().hasHeightForWidth())
        self.Pixelsize_2.setSizePolicy(sizePolicy)
        self.Pixelsize_2.setObjectName(_fromUtf8("Pixelsize_2"))
        self.Pixelsize.addWidget(self.Pixelsize_2)
        self.PixelsizeSelector = QtGui.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PixelsizeSelector.sizePolicy().hasHeightForWidth())
        self.PixelsizeSelector.setSizePolicy(sizePolicy)
        self.PixelsizeSelector.setDecimals(3)
        self.PixelsizeSelector.setProperty("value", 0.5)
        self.PixelsizeSelector.setObjectName(_fromUtf8("PixelsizeSelector"))
        self.Pixelsize.addWidget(self.PixelsizeSelector)
        self.verticalLayout.addLayout(self.Pixelsize)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.CadenceSelector = QtGui.QSpinBox(self.layoutWidget3)
        self.CadenceSelector.setMaximum(100000)
        self.CadenceSelector.setProperty("value", 45)
        self.CadenceSelector.setObjectName(_fromUtf8("CadenceSelector"))
        self.horizontalLayout_2.addWidget(self.CadenceSelector)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget4 = QtGui.QWidget(self.Options_CalcgroupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 160, 321, 41))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.labelInit = QtGui.QLabel(self.layoutWidget4)
        self.labelInit.setObjectName(_fromUtf8("labelInit"))
        self.horizontalLayout_34.addWidget(self.labelInit)
        self.spinBoxInit = QtGui.QSpinBox(self.layoutWidget4)
        self.spinBoxInit.setMaximum(9999)
        self.spinBoxInit.setObjectName(_fromUtf8("spinBoxInit"))
        self.horizontalLayout_34.addWidget(self.spinBoxInit)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.labelEnd = QtGui.QLabel(self.layoutWidget4)
        self.labelEnd.setObjectName(_fromUtf8("labelEnd"))
        self.horizontalLayout_35.addWidget(self.labelEnd)
        self.spinBoxEnd = QtGui.QSpinBox(self.layoutWidget4)
        self.spinBoxEnd.setMaximum(9999)
        self.spinBoxEnd.setProperty("value", 20)
        self.spinBoxEnd.setObjectName(_fromUtf8("spinBoxEnd"))
        self.horizontalLayout_35.addWidget(self.spinBoxEnd)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_35)
        self.vectorOptiongroupBox = QtGui.QGroupBox(self.tab_3)
        self.vectorOptiongroupBox.setGeometry(QtCore.QRect(10, 330, 341, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setUnderline(False)
        self.vectorOptiongroupBox.setFont(font)
        self.vectorOptiongroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.vectorOptiongroupBox.setObjectName(_fromUtf8("vectorOptiongroupBox"))
        self.layoutWidget5 = QtGui.QWidget(self.vectorOptiongroupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 321, 231))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Pixel = QtGui.QHBoxLayout()
        self.Pixel.setObjectName(_fromUtf8("Pixel"))
        self.Pixel_2 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pixel_2.sizePolicy().hasHeightForWidth())
        self.Pixel_2.setSizePolicy(sizePolicy)
        self.Pixel_2.setObjectName(_fromUtf8("Pixel_2"))
        self.Pixel.addWidget(self.Pixel_2)
        self.PixelSelector = QtGui.QSpinBox(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PixelSelector.sizePolicy().hasHeightForWidth())
        self.PixelSelector.setSizePolicy(sizePolicy)
        self.PixelSelector.setProperty("value", 10)
        self.PixelSelector.setObjectName(_fromUtf8("PixelSelector"))
        self.Pixel.addWidget(self.PixelSelector)
        self.verticalLayout_2.addLayout(self.Pixel)
        self.Color = QtGui.QHBoxLayout()
        self.Color.setObjectName(_fromUtf8("Color"))
        self.Color_2 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color_2.sizePolicy().hasHeightForWidth())
        self.Color_2.setSizePolicy(sizePolicy)
        self.Color_2.setObjectName(_fromUtf8("Color_2"))
        self.Color.addWidget(self.Color_2)
        self.ColorSelector = QtGui.QPushButton(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorSelector.sizePolicy().hasHeightForWidth())
        self.ColorSelector.setSizePolicy(sizePolicy)
        self.ColorSelector.setObjectName(_fromUtf8("ColorSelector"))
        self.Color.addWidget(self.ColorSelector)
        self.verticalLayout_2.addLayout(self.Color)
        self.Pivot = QtGui.QHBoxLayout()
        self.Pivot.setObjectName(_fromUtf8("Pivot"))
        self.Pivot_2 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pivot_2.sizePolicy().hasHeightForWidth())
        self.Pivot_2.setSizePolicy(sizePolicy)
        self.Pivot_2.setObjectName(_fromUtf8("Pivot_2"))
        self.Pivot.addWidget(self.Pivot_2)
        self.PivotSelector = QtGui.QComboBox(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PivotSelector.sizePolicy().hasHeightForWidth())
        self.PivotSelector.setSizePolicy(sizePolicy)
        self.PivotSelector.setObjectName(_fromUtf8("PivotSelector"))
        self.PivotSelector.addItem(_fromUtf8(""))
        self.PivotSelector.addItem(_fromUtf8(""))
        self.PivotSelector.addItem(_fromUtf8(""))
        self.Pivot.addWidget(self.PivotSelector)
        self.verticalLayout_2.addLayout(self.Pivot)
        self.Width = QtGui.QHBoxLayout()
        self.Width.setObjectName(_fromUtf8("Width"))
        self.Width_2 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Width_2.sizePolicy().hasHeightForWidth())
        self.Width_2.setSizePolicy(sizePolicy)
        self.Width_2.setObjectName(_fromUtf8("Width_2"))
        self.Width.addWidget(self.Width_2)
        self.WidthSelector = QtGui.QDoubleSpinBox(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidthSelector.sizePolicy().hasHeightForWidth())
        self.WidthSelector.setSizePolicy(sizePolicy)
        self.WidthSelector.setDecimals(6)
        self.WidthSelector.setMinimum(1e-05)
        self.WidthSelector.setSingleStep(0.01)
        self.WidthSelector.setProperty("value", 1.5)
        self.WidthSelector.setObjectName(_fromUtf8("WidthSelector"))
        self.Width.addWidget(self.WidthSelector)
        self.verticalLayout_2.addLayout(self.Width)
        self.Scale = QtGui.QHBoxLayout()
        self.Scale.setObjectName(_fromUtf8("Scale"))
        self.Scale_2 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale_2.sizePolicy().hasHeightForWidth())
        self.Scale_2.setSizePolicy(sizePolicy)
        self.Scale_2.setObjectName(_fromUtf8("Scale_2"))
        self.Scale.addWidget(self.Scale_2)
        self.ScaleSelector = QtGui.QDoubleSpinBox(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleSelector.sizePolicy().hasHeightForWidth())
        self.ScaleSelector.setSizePolicy(sizePolicy)
        self.ScaleSelector.setDecimals(4)
        self.ScaleSelector.setProperty("value", 0.17)
        self.ScaleSelector.setObjectName(_fromUtf8("ScaleSelector"))
        self.Scale.addWidget(self.ScaleSelector)
        self.verticalLayout_2.addLayout(self.Scale)
        self.Units = QtGui.QHBoxLayout()
        self.Units.setObjectName(_fromUtf8("Units"))
        self.Units_2 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units_2.sizePolicy().hasHeightForWidth())
        self.Units_2.setSizePolicy(sizePolicy)
        self.Units_2.setObjectName(_fromUtf8("Units_2"))
        self.Units.addWidget(self.Units_2)
        self.UnitsSelector = QtGui.QComboBox(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnitsSelector.sizePolicy().hasHeightForWidth())
        self.UnitsSelector.setSizePolicy(sizePolicy)
        self.UnitsSelector.setObjectName(_fromUtf8("UnitsSelector"))
        self.UnitsSelector.addItem(_fromUtf8(""))
        self.UnitsSelector.addItem(_fromUtf8(""))
        self.Units.addWidget(self.UnitsSelector)
        self.verticalLayout_2.addLayout(self.Units)
        self.layoutWidget6 = QtGui.QWidget(self.tab_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(70, 677, 221, 32))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.PlotClear = QtGui.QHBoxLayout(self.layoutWidget6)
        self.PlotClear.setObjectName(_fromUtf8("PlotClear"))
        self.maskPushButton = QtGui.QPushButton(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskPushButton.sizePolicy().hasHeightForWidth())
        self.maskPushButton.setSizePolicy(sizePolicy)
        self.maskPushButton.setObjectName(_fromUtf8("maskPushButton"))
        self.PlotClear.addWidget(self.maskPushButton)
        self.fullImageButton = QtGui.QPushButton(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullImageButton.sizePolicy().hasHeightForWidth())
        self.fullImageButton.setSizePolicy(sizePolicy)
        self.fullImageButton.setObjectName(_fromUtf8("fullImageButton"))
        self.PlotClear.addWidget(self.fullImageButton)
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(270, 300, 70, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.vmasklabel = QtGui.QLabel(self.tab_3)
        self.vmasklabel.setGeometry(QtCore.QRect(60, 590, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.vmasklabel.setFont(font)
        self.vmasklabel.setObjectName(_fromUtf8("vmasklabel"))
        self.masklabel = QtGui.QLabel(self.tab_3)
        self.masklabel.setGeometry(QtCore.QRect(210, 587, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.masklabel.setFont(font)
        self.masklabel.setObjectName(_fromUtf8("masklabel"))
        self.layoutWidget7 = QtGui.QWidget(self.tab_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(50, 610, 111, 62))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.vminlabel_5 = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(10)
        self.vminlabel_5.setFont(font)
        self.vminlabel_5.setObjectName(_fromUtf8("vminlabel_5"))
        self.horizontalLayout_23.addWidget(self.vminlabel_5)
        self.vminlineEdit = QtGui.QLineEdit(self.layoutWidget7)
        self.vminlineEdit.setObjectName(_fromUtf8("vminlineEdit"))
        self.horizontalLayout_23.addWidget(self.vminlineEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.vmaxlabel_6 = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(10)
        self.vmaxlabel_6.setFont(font)
        self.vmaxlabel_6.setObjectName(_fromUtf8("vmaxlabel_6"))
        self.horizontalLayout_25.addWidget(self.vmaxlabel_6)
        self.vmaxlineEdit = QtGui.QLineEdit(self.layoutWidget7)
        self.vmaxlineEdit.setObjectName(_fromUtf8("vmaxlineEdit"))
        self.horizontalLayout_25.addWidget(self.vmaxlineEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.layoutWidget8 = QtGui.QWidget(self.tab_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(200, 610, 101, 62))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.iminlabel_7 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(10)
        self.iminlabel_7.setFont(font)
        self.iminlabel_7.setObjectName(_fromUtf8("iminlabel_7"))
        self.horizontalLayout_24.addWidget(self.iminlabel_7)
        self.iminlineEdit = QtGui.QLineEdit(self.layoutWidget8)
        self.iminlineEdit.setObjectName(_fromUtf8("iminlineEdit"))
        self.horizontalLayout_24.addWidget(self.iminlineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.imaxlabel_8 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(10)
        self.imaxlabel_8.setFont(font)
        self.imaxlabel_8.setObjectName(_fromUtf8("imaxlabel_8"))
        self.horizontalLayout_26.addWidget(self.imaxlabel_8)
        self.imaxlineEdit = QtGui.QLineEdit(self.layoutWidget8)
        self.imaxlineEdit.setObjectName(_fromUtf8("imaxlineEdit"))
        self.horizontalLayout_26.addWidget(self.imaxlineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.closeButton_1 = QtGui.QPushButton(self.tab_3)
        self.closeButton_1.setGeometry(QtCore.QRect(290, 720, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closeButton_1.setFont(font)
        self.closeButton_1.setObjectName(_fromUtf8("closeButton_1"))
        #self.MDToolstabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.SaveHist_pushButton = QtGui.QPushButton(self.tab_4)
        self.SaveHist_pushButton.setGeometry(QtCore.QRect(10, 700, 121, 32))
        self.SaveHist_pushButton.setObjectName(_fromUtf8("SaveHist_pushButton"))
        self.closeButton_2 = QtGui.QPushButton(self.tab_4)
        self.closeButton_2.setGeometry(QtCore.QRect(250, 700, 110, 32))
        self.closeButton_2.setObjectName(_fromUtf8("closeButton_2"))
        self.layoutWidget9 = QtGui.QWidget(self.tab_4)
        self.layoutWidget9.setGeometry(QtCore.QRect(1, 1, 361, 691))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.histoverticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.histoverticalLayout_12.setObjectName(_fromUtf8("histoverticalLayout_12"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.Intruc_histolabel_2 = QtGui.QLabel(self.layoutWidget9)
        self.Intruc_histolabel_2.setObjectName(_fromUtf8("Intruc_histolabel_2"))
        self.horizontalLayout_20.addWidget(self.Intruc_histolabel_2, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.histo_plainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histo_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.histo_plainTextEdit.setSizePolicy(sizePolicy)
        self.histo_plainTextEdit.setMinimumSize(QtCore.QSize(0, 70))
        self.histo_plainTextEdit.setMaximumSize(QtCore.QSize(256, 70))
        self.histo_plainTextEdit.setReadOnly(True)
        self.histo_plainTextEdit.setObjectName(_fromUtf8("histo_plainTextEdit"))
        self.verticalLayout_9.addWidget(self.histo_plainTextEdit, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.histoverticalLayout_12.addLayout(self.verticalLayout_9)
        self.widget_2 = QtGui.QWidget(self.layoutWidget9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.histoverticalLayout_12.addWidget(self.widget_2)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.RegionpushButton_2 = QtGui.QPushButton(self.layoutWidget9)
        self.RegionpushButton_2.setObjectName(_fromUtf8("RegionpushButton_2"))
        self.horizontalLayout_12.addWidget(self.RegionpushButton_2)
        self.fullhistpushButton = QtGui.QPushButton(self.layoutWidget9)
        self.fullhistpushButton.setObjectName(_fromUtf8("fullhistpushButton"))
        self.horizontalLayout_12.addWidget(self.fullhistpushButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.pixelradioButton = QtGui.QRadioButton(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.pixelradioButton.setFont(font)
        self.pixelradioButton.setChecked(True)
        self.pixelradioButton.setObjectName(_fromUtf8("pixelradioButton"))
        self.horizontalLayout_16.addWidget(self.pixelradioButton)
        self.velocityradioButton_2 = QtGui.QRadioButton(self.layoutWidget9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityradioButton_2.sizePolicy().hasHeightForWidth())
        self.velocityradioButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.velocityradioButton_2.setFont(font)
        self.velocityradioButton_2.setObjectName(_fromUtf8("velocityradioButton_2"))
        self.horizontalLayout_16.addWidget(self.velocityradioButton_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.checkBoxFit = QtGui.QCheckBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.checkBoxFit.setFont(font)
        self.checkBoxFit.setObjectName(_fromUtf8("checkBoxFit"))
        self.horizontalLayout_17.addWidget(self.checkBoxFit)
        self.LOGcheckBox = QtGui.QCheckBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.LOGcheckBox.setFont(font)
        self.LOGcheckBox.setObjectName(_fromUtf8("LOGcheckBox"))
        self.horizontalLayout_17.addWidget(self.LOGcheckBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.propertiesButton = QtGui.QPushButton(self.layoutWidget9)
        self.propertiesButton.setObjectName(_fromUtf8("propertiesButton"))
        self.horizontalLayout_21.addWidget(self.propertiesButton)
        self.fitButton = QtGui.QPushButton(self.layoutWidget9)
        self.fitButton.setObjectName(_fromUtf8("fitButton"))
        self.horizontalLayout_21.addWidget(self.fitButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.histoverticalLayout_12.addLayout(self.verticalLayout_10)
        #self.MDToolstabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.diverlabel_5 = QtGui.QLabel(self.tab_5)
        self.diverlabel_5.setGeometry(QtCore.QRect(140, 0, 81, 16))
        self.diverlabel_5.setObjectName(_fromUtf8("diverlabel_5"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_5)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 20, 251, 51))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.ImProptabWidget_2 = QtGui.QTabWidget(self.tab_5)
        self.ImProptabWidget_2.setGeometry(QtCore.QRect(10, 90, 351, 631))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImProptabWidget_2.sizePolicy().hasHeightForWidth())
        self.ImProptabWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Amiri Quran"))
        font.setPointSize(8)
        self.ImProptabWidget_2.setFont(font)
        self.ImProptabWidget_2.setTabsClosable(True)
        self.ImProptabWidget_2.setObjectName(_fromUtf8("ImProptabWidget_2"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.cmaptoolButton = QtGui.QToolButton(self.tab_8)
        self.cmaptoolButton.setGeometry(QtCore.QRect(110, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        self.cmaptoolButton.setFont(font)
        self.cmaptoolButton.setObjectName(_fromUtf8("cmaptoolButton"))
        self.layoutWidget10 = QtGui.QWidget(self.tab_8)
        self.layoutWidget10.setGeometry(QtCore.QRect(30, 60, 251, 86))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Amiri Quran"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Amiri Quran"))
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.layoutWidget11 = QtGui.QWidget(self.tab_8)
        self.layoutWidget11.setGeometry(QtCore.QRect(80, 350, 181, 81))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.vecradioButton = QtGui.QRadioButton(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vecradioButton.setFont(font)
        self.vecradioButton.setChecked(True)
        self.vecradioButton.setObjectName(_fromUtf8("vecradioButton"))
        self.horizontalLayout_13.addWidget(self.vecradioButton)
        self.contourradioButton = QtGui.QRadioButton(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contourradioButton.setFont(font)
        self.contourradioButton.setObjectName(_fromUtf8("contourradioButton"))
        self.horizontalLayout_13.addWidget(self.contourradioButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.plot_diverpushButton = QtGui.QPushButton(self.layoutWidget11)
        self.plot_diverpushButton.setObjectName(_fromUtf8("plot_diverpushButton"))
        self.horizontalLayout_14.addWidget(self.plot_diverpushButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.AmpliTitleLabel = QtGui.QLabel(self.tab_8)
        self.AmpliTitleLabel.setGeometry(QtCore.QRect(90, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.AmpliTitleLabel.setFont(font)
        self.AmpliTitleLabel.setObjectName(_fromUtf8("AmpliTitleLabel"))
        self.layoutWidget12 = QtGui.QWidget(self.tab_8)
        self.layoutWidget12.setGeometry(QtCore.QRect(50, 180, 221, 41))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.AmplificatorSlider = QtGui.QSlider(self.layoutWidget12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AmplificatorSlider.sizePolicy().hasHeightForWidth())
        self.AmplificatorSlider.setSizePolicy(sizePolicy)
        self.AmplificatorSlider.setMinimum(1)
        self.AmplificatorSlider.setMaximum(500)
        self.AmplificatorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AmplificatorSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.AmplificatorSlider.setTickInterval(50)
        self.AmplificatorSlider.setObjectName(_fromUtf8("AmplificatorSlider"))
        self.horizontalLayout_32.addWidget(self.AmplificatorSlider)
        spacerItem7 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem7)
        self.Amplificatorlabel = QtGui.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Amplificatorlabel.setFont(font)
        self.Amplificatorlabel.setObjectName(_fromUtf8("Amplificatorlabel"))
        self.horizontalLayout_32.addWidget(self.Amplificatorlabel)
        self.layoutWidget13 = QtGui.QWidget(self.tab_8)
        self.layoutWidget13.setGeometry(QtCore.QRect(90, 240, 151, 41))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.alphaTitleLabel = QtGui.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.alphaTitleLabel.setFont(font)
        self.alphaTitleLabel.setObjectName(_fromUtf8("alphaTitleLabel"))
        self.horizontalLayout_33.addWidget(self.alphaTitleLabel)
        self.alphalineEdit = QtGui.QLineEdit(self.layoutWidget13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.alphalineEdit.setFont(font)
        self.alphalineEdit.setObjectName(_fromUtf8("alphalineEdit"))
        self.horizontalLayout_33.addWidget(self.alphalineEdit)
        self.ImProptabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.layoutWidget14 = QtGui.QWidget(self.tab_9)
        self.layoutWidget14.setGeometry(QtCore.QRect(70, 70, 221, 296))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Pixel_3 = QtGui.QHBoxLayout()
        self.Pixel_3.setObjectName(_fromUtf8("Pixel_3"))
        self.Pixel_4 = QtGui.QLabel(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pixel_4.sizePolicy().hasHeightForWidth())
        self.Pixel_4.setSizePolicy(sizePolicy)
        self.Pixel_4.setObjectName(_fromUtf8("Pixel_4"))
        self.Pixel_3.addWidget(self.Pixel_4)
        self.PixelSelector_2 = QtGui.QSpinBox(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PixelSelector_2.sizePolicy().hasHeightForWidth())
        self.PixelSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PixelSelector_2.setFont(font)
        self.PixelSelector_2.setProperty("value", 10)
        self.PixelSelector_2.setObjectName(_fromUtf8("PixelSelector_2"))
        self.Pixel_3.addWidget(self.PixelSelector_2)
        self.verticalLayout_4.addLayout(self.Pixel_3)
        self.Color_3 = QtGui.QHBoxLayout()
        self.Color_3.setObjectName(_fromUtf8("Color_3"))
        self.Color_4 = QtGui.QLabel(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color_4.sizePolicy().hasHeightForWidth())
        self.Color_4.setSizePolicy(sizePolicy)
        self.Color_4.setObjectName(_fromUtf8("Color_4"))
        self.Color_3.addWidget(self.Color_4)
        self.ColorSelector_2 = QtGui.QPushButton(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorSelector_2.sizePolicy().hasHeightForWidth())
        self.ColorSelector_2.setSizePolicy(sizePolicy)
        self.ColorSelector_2.setObjectName(_fromUtf8("ColorSelector_2"))
        self.Color_3.addWidget(self.ColorSelector_2)
        self.verticalLayout_4.addLayout(self.Color_3)
        self.Pivot_3 = QtGui.QHBoxLayout()
        self.Pivot_3.setObjectName(_fromUtf8("Pivot_3"))
        self.Pivot_4 = QtGui.QLabel(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pivot_4.sizePolicy().hasHeightForWidth())
        self.Pivot_4.setSizePolicy(sizePolicy)
        self.Pivot_4.setObjectName(_fromUtf8("Pivot_4"))
        self.Pivot_3.addWidget(self.Pivot_4)
        self.PivotSelector_2 = QtGui.QComboBox(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PivotSelector_2.sizePolicy().hasHeightForWidth())
        self.PivotSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PivotSelector_2.setFont(font)
        self.PivotSelector_2.setObjectName(_fromUtf8("PivotSelector_2"))
        self.PivotSelector_2.addItem(_fromUtf8(""))
        self.PivotSelector_2.addItem(_fromUtf8(""))
        self.PivotSelector_2.addItem(_fromUtf8(""))
        self.Pivot_3.addWidget(self.PivotSelector_2)
        self.verticalLayout_4.addLayout(self.Pivot_3)
        self.Width_3 = QtGui.QHBoxLayout()
        self.Width_3.setObjectName(_fromUtf8("Width_3"))
        self.Width_4 = QtGui.QLabel(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Width_4.sizePolicy().hasHeightForWidth())
        self.Width_4.setSizePolicy(sizePolicy)
        self.Width_4.setObjectName(_fromUtf8("Width_4"))
        self.Width_3.addWidget(self.Width_4)
        self.WidthSelector_2 = QtGui.QDoubleSpinBox(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidthSelector_2.sizePolicy().hasHeightForWidth())
        self.WidthSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WidthSelector_2.setFont(font)
        self.WidthSelector_2.setDecimals(6)
        self.WidthSelector_2.setMinimum(1e-05)
        self.WidthSelector_2.setSingleStep(0.01)
        self.WidthSelector_2.setProperty("value", 1.5)
        self.WidthSelector_2.setObjectName(_fromUtf8("WidthSelector_2"))
        self.Width_3.addWidget(self.WidthSelector_2)
        self.verticalLayout_4.addLayout(self.Width_3)
        self.Scale_3 = QtGui.QHBoxLayout()
        self.Scale_3.setObjectName(_fromUtf8("Scale_3"))
        self.Scale_4 = QtGui.QLabel(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale_4.sizePolicy().hasHeightForWidth())
        self.Scale_4.setSizePolicy(sizePolicy)
        self.Scale_4.setObjectName(_fromUtf8("Scale_4"))
        self.Scale_3.addWidget(self.Scale_4)
        self.ScaleSelector_2 = QtGui.QDoubleSpinBox(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleSelector_2.sizePolicy().hasHeightForWidth())
        self.ScaleSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScaleSelector_2.setFont(font)
        self.ScaleSelector_2.setDecimals(4)
        self.ScaleSelector_2.setProperty("value", 0.17)
        self.ScaleSelector_2.setObjectName(_fromUtf8("ScaleSelector_2"))
        self.Scale_3.addWidget(self.ScaleSelector_2)
        self.verticalLayout_4.addLayout(self.Scale_3)
        self.Units_3 = QtGui.QHBoxLayout()
        self.Units_3.setObjectName(_fromUtf8("Units_3"))
        self.Units_4 = QtGui.QLabel(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units_4.sizePolicy().hasHeightForWidth())
        self.Units_4.setSizePolicy(sizePolicy)
        self.Units_4.setObjectName(_fromUtf8("Units_4"))
        self.Units_3.addWidget(self.Units_4)
        self.UnitsSelector_2 = QtGui.QComboBox(self.layoutWidget14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnitsSelector_2.sizePolicy().hasHeightForWidth())
        self.UnitsSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UnitsSelector_2.setFont(font)
        self.UnitsSelector_2.setObjectName(_fromUtf8("UnitsSelector_2"))
        self.UnitsSelector_2.addItem(_fromUtf8(""))
        self.UnitsSelector_2.addItem(_fromUtf8(""))
        self.Units_3.addWidget(self.UnitsSelector_2)
        self.verticalLayout_4.addLayout(self.Units_3)
        self.ImProptabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.CMAP_contourtoolButton = QtGui.QToolButton(self.tab_10)
        self.CMAP_contourtoolButton.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.CMAP_contourtoolButton.setObjectName(_fromUtf8("CMAP_contourtoolButton"))
        self.LevelgroupBox = QtGui.QGroupBox(self.tab_10)
        self.LevelgroupBox.setGeometry(QtCore.QRect(20, 310, 301, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.LevelgroupBox.setFont(font)
        self.LevelgroupBox.setObjectName(_fromUtf8("LevelgroupBox"))
        self.l1_radioButton = QtGui.QRadioButton(self.LevelgroupBox)
        self.l1_radioButton.setGeometry(QtCore.QRect(0, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1_radioButton.setFont(font)
        self.l1_radioButton.setChecked(True)
        self.l1_radioButton.setObjectName(_fromUtf8("l1_radioButton"))
        self.l2_radioButton_2 = QtGui.QRadioButton(self.LevelgroupBox)
        self.l2_radioButton_2.setGeometry(QtCore.QRect(0, 90, 105, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2_radioButton_2.setFont(font)
        self.l2_radioButton_2.setObjectName(_fromUtf8("l2_radioButton_2"))
        self.l3_radioButton_3 = QtGui.QRadioButton(self.LevelgroupBox)
        self.l3_radioButton_3.setGeometry(QtCore.QRect(0, 140, 105, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l3_radioButton_3.setFont(font)
        self.l3_radioButton_3.setObjectName(_fromUtf8("l3_radioButton_3"))
        self.sc_lineEdit_7 = QtGui.QLineEdit(self.LevelgroupBox)
        self.sc_lineEdit_7.setGeometry(QtCore.QRect(110, 40, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sc_lineEdit_7.setFont(font)
        self.sc_lineEdit_7.setPlaceholderText(_fromUtf8(""))
        self.sc_lineEdit_7.setObjectName(_fromUtf8("sc_lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.LevelgroupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 90, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.LevelgroupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 140, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.layoutWidget15 = QtGui.QWidget(self.tab_10)
        self.layoutWidget15.setGeometry(QtCore.QRect(20, 100, 161, 41))
        self.layoutWidget15.setObjectName(_fromUtf8("layoutWidget15"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.layoutWidget16 = QtGui.QWidget(self.tab_10)
        self.layoutWidget16.setGeometry(QtCore.QRect(20, 148, 291, 41))
        self.layoutWidget16.setObjectName(_fromUtf8("layoutWidget16"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget16)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.vaminlabel_8 = QtGui.QLabel(self.layoutWidget16)
        self.vaminlabel_8.setObjectName(_fromUtf8("vaminlabel_8"))
        self.horizontalLayout_6.addWidget(self.vaminlabel_8)
        self.vamindoubleSpinBox_2 = QtGui.QDoubleSpinBox(self.layoutWidget16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vamindoubleSpinBox_2.setFont(font)
        self.vamindoubleSpinBox_2.setObjectName(_fromUtf8("vamindoubleSpinBox_2"))
        self.horizontalLayout_6.addWidget(self.vamindoubleSpinBox_2)
        self.vamaxlabel_8 = QtGui.QLabel(self.layoutWidget16)
        self.vamaxlabel_8.setObjectName(_fromUtf8("vamaxlabel_8"))
        self.horizontalLayout_6.addWidget(self.vamaxlabel_8)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.layoutWidget16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_2)
        self.layoutWidget17 = QtGui.QWidget(self.tab_10)
        self.layoutWidget17.setGeometry(QtCore.QRect(20, 200, 291, 61))
        self.layoutWidget17.setObjectName(_fromUtf8("layoutWidget17"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget17)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.originlabel_8 = QtGui.QLabel(self.layoutWidget17)
        self.originlabel_8.setObjectName(_fromUtf8("originlabel_8"))
        self.horizontalLayout_7.addWidget(self.originlabel_8)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget17)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setInputMask(_fromUtf8(""))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.closeButton_3 = QtGui.QPushButton(self.tab_10)
        self.closeButton_3.setGeometry(QtCore.QRect(230, 570, 110, 32))
        self.closeButton_3.setObjectName(_fromUtf8("closeButton_3"))
        self.ImProptabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        #self.MDToolstabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.Instruc_overlabel_8 = QtGui.QLabel(self.tab_6)
        self.Instruc_overlabel_8.setGeometry(QtCore.QRect(130, 10, 81, 21))
        self.Instruc_overlabel_8.setObjectName(_fromUtf8("Instruc_overlabel_8"))
        self.overplainTextEdit_2 = QtGui.QPlainTextEdit(self.tab_6)
        self.overplainTextEdit_2.setGeometry(QtCore.QRect(60, 30, 241, 41))
        self.overplainTextEdit_2.setReadOnly(True)
        self.overplainTextEdit_2.setObjectName(_fromUtf8("overplainTextEdit_2"))
        self.limgroupBox = QtGui.QGroupBox(self.tab_6)
        self.limgroupBox.setGeometry(QtCore.QRect(20, 90, 331, 291))
        self.limgroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.limgroupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.limgroupBox.setObjectName(_fromUtf8("limgroupBox"))
        self.OverlaypushButton_4 = QtGui.QPushButton(self.limgroupBox)
        self.OverlaypushButton_4.setGeometry(QtCore.QRect(10, 260, 85, 26))
        self.OverlaypushButton_4.setObjectName(_fromUtf8("OverlaypushButton_4"))
        self.layoutWidget18 = QtGui.QWidget(self.limgroupBox)
        self.layoutWidget18.setGeometry(QtCore.QRect(10, 20, 311, 231))
        self.layoutWidget18.setObjectName(_fromUtf8("layoutWidget18"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget18)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.alfalabel_8 = QtGui.QLabel(self.layoutWidget18)
        self.alfalabel_8.setObjectName(_fromUtf8("alfalabel_8"))
        self.horizontalLayout_27.addWidget(self.alfalabel_8)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.layoutWidget18)
        self.doubleSpinBox_3.setMaximum(1.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 0.5)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.horizontalLayout_27.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.lowcollabel_9 = QtGui.QLabel(self.layoutWidget18)
        self.lowcollabel_9.setObjectName(_fromUtf8("lowcollabel_9"))
        self.horizontalLayout_28.addWidget(self.lowcollabel_9)
        self.chooselow_pushButton_2 = QtGui.QPushButton(self.layoutWidget18)
        self.chooselow_pushButton_2.setObjectName(_fromUtf8("chooselow_pushButton_2"))
        self.horizontalLayout_28.addWidget(self.chooselow_pushButton_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.lowlim_label_10 = QtGui.QLabel(self.layoutWidget18)
        self.lowlim_label_10.setObjectName(_fromUtf8("lowlim_label_10"))
        self.horizontalLayout_29.addWidget(self.lowlim_label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget18)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_29.addWidget(self.lineEdit_7, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.hicollabel_11 = QtGui.QLabel(self.layoutWidget18)
        self.hicollabel_11.setObjectName(_fromUtf8("hicollabel_11"))
        self.horizontalLayout_30.addWidget(self.hicollabel_11)
        self.hicolpushButton_3 = QtGui.QPushButton(self.layoutWidget18)
        self.hicolpushButton_3.setObjectName(_fromUtf8("hicolpushButton_3"))
        self.horizontalLayout_30.addWidget(self.hicolpushButton_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.hilim_label_12 = QtGui.QLabel(self.layoutWidget18)
        self.hilim_label_12.setObjectName(_fromUtf8("hilim_label_12"))
        self.horizontalLayout_31.addWidget(self.hilim_label_12)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget18)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_31.addWidget(self.lineEdit_10, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.closeButton_4 = QtGui.QPushButton(self.tab_6)
        self.closeButton_4.setGeometry(QtCore.QRect(240, 700, 110, 32))
        self.closeButton_4.setObjectName(_fromUtf8("closeButton_4"))
        self.ContrastTitle = QtGui.QLabel(self.tab_6)
        self.ContrastTitle.setGeometry(QtCore.QRect(140, 440, 91, 31))
        self.ContrastTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.ContrastTitle.setObjectName(_fromUtf8("ContrastTitle"))
        self.layoutWidget19 = QtGui.QWidget(self.tab_6)
        self.layoutWidget19.setGeometry(QtCore.QRect(21, 481, 331, 74))
        self.layoutWidget19.setObjectName(_fromUtf8("layoutWidget19"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.layoutWidget19)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.CutLowlabel = QtGui.QLabel(self.layoutWidget19)
        self.CutLowlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.CutLowlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CutLowlabel.setObjectName(_fromUtf8("CutLowlabel"))
        self.verticalLayout_14.addWidget(self.CutLowlabel)
        self.numLowlabel = QtGui.QLabel(self.layoutWidget19)
        self.numLowlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.numLowlabel.setText(_fromUtf8(""))
        self.numLowlabel.setObjectName(_fromUtf8("numLowlabel"))
        self.verticalLayout_14.addWidget(self.numLowlabel)
        self.horizontalLayout_37.addLayout(self.verticalLayout_14)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalSliderLow = QtGui.QSlider(self.layoutWidget19)
        self.horizontalSliderLow.setMinimum(0)
        self.horizontalSliderLow.setMaximum(99)
        self.horizontalSliderLow.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderLow.setInvertedControls(True)
        self.horizontalSliderLow.setObjectName(_fromUtf8("horizontalSliderLow"))
        self.horizontalLayout_22.addWidget(self.horizontalSliderLow)
        self.horizontalSliderHigh = QtGui.QSlider(self.layoutWidget19)
        self.horizontalSliderHigh.setProperty("value", 99)
        self.horizontalSliderHigh.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderHigh.setInvertedAppearance(False)
        self.horizontalSliderHigh.setInvertedControls(True)
        self.horizontalSliderHigh.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSliderHigh.setObjectName(_fromUtf8("horizontalSliderHigh"))
        self.horizontalLayout_22.addWidget(self.horizontalSliderHigh)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_22)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.CutHighlabel = QtGui.QLabel(self.layoutWidget19)
        self.CutHighlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.CutHighlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CutHighlabel.setObjectName(_fromUtf8("CutHighlabel"))
        self.verticalLayout_15.addWidget(self.CutHighlabel)
        self.numHighlabel = QtGui.QLabel(self.layoutWidget19)
        self.numHighlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.numHighlabel.setText(_fromUtf8(""))
        self.numHighlabel.setObjectName(_fromUtf8("numHighlabel"))
        self.verticalLayout_15.addWidget(self.numHighlabel)
        self.horizontalLayout_37.addLayout(self.verticalLayout_15)
        #self.MDToolstabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(60, 30, 231, 61))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.start_lassoButton = QtGui.QPushButton(self.tab)
        self.start_lassoButton.setGeometry(QtCore.QRect(50, 110, 110, 32))
        self.start_lassoButton.setObjectName(_fromUtf8("start_lassoButton"))
        self.stop_lassoButton = QtGui.QPushButton(self.tab)
        self.stop_lassoButton.setGeometry(QtCore.QRect(190, 110, 110, 32))
        self.stop_lassoButton.setObjectName(_fromUtf8("stop_lassoButton"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(150, 230, 56, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.statisticsplainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.statisticsplainTextEdit.setGeometry(QtCore.QRect(60, 260, 251, 321))
        self.statisticsplainTextEdit.setObjectName(_fromUtf8("statisticsplainTextEdit"))
        self.LassoMaskpushButton = QtGui.QPushButton(self.tab)
        self.LassoMaskpushButton.setGeometry(QtCore.QRect(120, 160, 110, 32))
        self.LassoMaskpushButton.setObjectName(_fromUtf8("LassoMaskpushButton"))
        self.closeButton_5 = QtGui.QPushButton(self.tab)
        self.closeButton_5.setGeometry(QtCore.QRect(240, 700, 110, 32))
        self.closeButton_5.setObjectName(_fromUtf8("closeButton_5"))
        #self.MDToolstabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.instruc_md_label_8 = QtGui.QLabel(self.tab_7)
        self.instruc_md_label_8.setGeometry(QtCore.QRect(130, 10, 81, 16))
        self.instruc_md_label_8.setObjectName(_fromUtf8("instruc_md_label_8"))
        self.Instruc_md_plainTextEdit_2 = QtGui.QPlainTextEdit(self.tab_7)
        self.Instruc_md_plainTextEdit_2.setGeometry(QtCore.QRect(50, 30, 251, 51))
        self.Instruc_md_plainTextEdit_2.setReadOnly(True)
        self.Instruc_md_plainTextEdit_2.setObjectName(_fromUtf8("Instruc_md_plainTextEdit_2"))
        self.hdu_label_8 = QtGui.QLabel(self.tab_7)
        self.hdu_label_8.setGeometry(QtCore.QRect(150, 90, 31, 16))
        self.hdu_label_8.setObjectName(_fromUtf8("hdu_label_8"))
        self.naxis_label_8 = QtGui.QLabel(self.tab_7)
        self.naxis_label_8.setGeometry(QtCore.QRect(110, 110, 121, 21))
        self.naxis_label_8.setObjectName(_fromUtf8("naxis_label_8"))
        self.na1_label_8 = QtGui.QLabel(self.tab_7)
        self.na1_label_8.setGeometry(QtCore.QRect(10, 150, 58, 15))
        self.na1_label_8.setObjectName(_fromUtf8("na1_label_8"))
        self.na2_label_9 = QtGui.QLabel(self.tab_7)
        self.na2_label_9.setGeometry(QtCore.QRect(10, 180, 58, 15))
        self.na2_label_9.setObjectName(_fromUtf8("na2_label_9"))
        self.na3_label_10 = QtGui.QLabel(self.tab_7)
        self.na3_label_10.setGeometry(QtCore.QRect(10, 210, 58, 15))
        self.na3_label_10.setObjectName(_fromUtf8("na3_label_10"))
        self.na1_val_label_8 = QtGui.QLabel(self.tab_7)
        self.na1_val_label_8.setGeometry(QtCore.QRect(70, 150, 31, 16))
        self.na1_val_label_8.setText(_fromUtf8(""))
        self.na1_val_label_8.setObjectName(_fromUtf8("na1_val_label_8"))
        self.na2_val_label_8 = QtGui.QLabel(self.tab_7)
        self.na2_val_label_8.setGeometry(QtCore.QRect(70, 180, 31, 16))
        self.na2_val_label_8.setText(_fromUtf8(""))
        self.na2_val_label_8.setObjectName(_fromUtf8("na2_val_label_8"))
        self.na3_val_label_8 = QtGui.QLabel(self.tab_7)
        self.na3_val_label_8.setGeometry(QtCore.QRect(70, 210, 31, 16))
        self.na3_val_label_8.setText(_fromUtf8(""))
        self.na3_val_label_8.setObjectName(_fromUtf8("na3_val_label_8"))
        self.horizontalSlider = QtGui.QSlider(self.tab_7)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 205, 131, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(20)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.slice_label_8 = QtGui.QLabel(self.tab_7)
        self.slice_label_8.setGeometry(QtCore.QRect(90, 400, 51, 31))
        self.slice_label_8.setObjectName(_fromUtf8("slice_label_8"))
        self.nslice_label_8 = QtGui.QLabel(self.tab_7)
        self.nslice_label_8.setGeometry(QtCore.QRect(150, 400, 61, 31))
        self.nslice_label_8.setText(_fromUtf8(""))
        self.nslice_label_8.setObjectName(_fromUtf8("nslice_label_8"))
        self.layoutWidget20 = QtGui.QWidget(self.tab_7)
        self.layoutWidget20.setGeometry(QtCore.QRect(70, 340, 221, 51))
        self.layoutWidget20.setObjectName(_fromUtf8("layoutWidget20"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget20)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.framelabel_8 = QtGui.QLabel(self.layoutWidget20)
        self.framelabel_8.setObjectName(_fromUtf8("framelabel_8"))
        self.horizontalLayout_11.addWidget(self.framelabel_8)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.layoutWidget20)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_4)
        self.layoutWidget21 = QtGui.QWidget(self.tab_7)
        self.layoutWidget21.setGeometry(QtCore.QRect(40, 240, 271, 76))
        self.layoutWidget21.setObjectName(_fromUtf8("layoutWidget21"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget21)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.firstpushButton_2 = QtGui.QPushButton(self.layoutWidget21)
        self.firstpushButton_2.setObjectName(_fromUtf8("firstpushButton_2"))
        self.horizontalLayout_9.addWidget(self.firstpushButton_2)
        self.prev_pushButton_3 = QtGui.QPushButton(self.layoutWidget21)
        self.prev_pushButton_3.setObjectName(_fromUtf8("prev_pushButton_3"))
        self.horizontalLayout_9.addWidget(self.prev_pushButton_3)
        self.stoppushButton_4 = QtGui.QPushButton(self.layoutWidget21)
        self.stoppushButton_4.setObjectName(_fromUtf8("stoppushButton_4"))
        self.horizontalLayout_9.addWidget(self.stoppushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.endpushButton_5 = QtGui.QPushButton(self.layoutWidget21)
        self.endpushButton_5.setObjectName(_fromUtf8("endpushButton_5"))
        self.horizontalLayout_10.addWidget(self.endpushButton_5)
        self.nextpushButton_6 = QtGui.QPushButton(self.layoutWidget21)
        self.nextpushButton_6.setObjectName(_fromUtf8("nextpushButton_6"))
        self.horizontalLayout_10.addWidget(self.nextpushButton_6)
        self.playpushButton_7 = QtGui.QPushButton(self.layoutWidget21)
        self.playpushButton_7.setObjectName(_fromUtf8("playpushButton_7"))
        self.horizontalLayout_10.addWidget(self.playpushButton_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.closeButton_6 = QtGui.QPushButton(self.tab_7)
        self.closeButton_6.setGeometry(QtCore.QRect(230, 690, 110, 32))
        self.closeButton_6.setObjectName(_fromUtf8("closeButton_6"))
        #self.MDToolstabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.zoomgroupBox = QtGui.QGroupBox(self.centralwidget)
        self.zoomgroupBox.setGeometry(QtCore.QRect(20, 610, 241, 81))
        self.zoomgroupBox.setObjectName(_fromUtf8("zoomgroupBox"))
        self.xinf_spinBox = QtGui.QSpinBox(self.zoomgroupBox)
        self.xinf_spinBox.setGeometry(QtCore.QRect(70, 20, 47, 24))
        self.xinf_spinBox.setMaximum(10000)
        self.xinf_spinBox.setObjectName(_fromUtf8("xinf_spinBox"))
        self.yinf_spinBox_2 = QtGui.QSpinBox(self.zoomgroupBox)
        self.yinf_spinBox_2.setGeometry(QtCore.QRect(70, 50, 47, 24))
        self.yinf_spinBox_2.setMaximum(10000)
        self.yinf_spinBox_2.setObjectName(_fromUtf8("yinf_spinBox_2"))
        self.ysup_spinBox_3 = QtGui.QSpinBox(self.zoomgroupBox)
        self.ysup_spinBox_3.setGeometry(QtCore.QRect(190, 50, 47, 24))
        self.ysup_spinBox_3.setMaximum(10000)
        self.ysup_spinBox_3.setObjectName(_fromUtf8("ysup_spinBox_3"))
        self.xsup_spinBox_4 = QtGui.QSpinBox(self.zoomgroupBox)
        self.xsup_spinBox_4.setGeometry(QtCore.QRect(190, 20, 47, 24))
        self.xsup_spinBox_4.setMaximum(10000)
        self.xsup_spinBox_4.setObjectName(_fromUtf8("xsup_spinBox_4"))
        self.xinf_label = QtGui.QLabel(self.zoomgroupBox)
        self.xinf_label.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.xinf_label.setObjectName(_fromUtf8("xinf_label"))
        self.yinf_label_2 = QtGui.QLabel(self.zoomgroupBox)
        self.yinf_label_2.setGeometry(QtCore.QRect(30, 50, 31, 16))
        self.yinf_label_2.setObjectName(_fromUtf8("yinf_label_2"))
        self.xsup_label_3 = QtGui.QLabel(self.zoomgroupBox)
        self.xsup_label_3.setGeometry(QtCore.QRect(160, 20, 31, 16))
        self.xsup_label_3.setObjectName(_fromUtf8("xsup_label_3"))
        self.ysup_label_4 = QtGui.QLabel(self.zoomgroupBox)
        self.ysup_label_4.setGeometry(QtCore.QRect(160, 50, 31, 16))
        self.ysup_label_4.setObjectName(_fromUtf8("ysup_label_4"))
        self.PlotRegionpushButton = QtGui.QPushButton(self.centralwidget)
        self.PlotRegionpushButton.setGeometry(QtCore.QRect(150, 710, 111, 31))
        self.PlotRegionpushButton.setObjectName(_fromUtf8("PlotRegionpushButton"))
        self.ImagetabWidget_2.raise_()
        self.RestorepushButton_2.raise_()
        self.tabWidget.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.layoutWidget.raise_()
        self.Message.raise_()
        self.MDToolstabWidget_2.raise_()
        self.zoomgroupBox.raise_()
        self.PlotRegionpushButton.raise_()
        FlowsMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FlowsMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1421, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOperation = QtGui.QMenu(self.menubar)
        self.menuOperation.setObjectName(_fromUtf8("menuOperation"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        FlowsMainWindow.setMenuBar(self.menubar)
        self.menutoolBar = QtGui.QToolBar(FlowsMainWindow)
        self.menutoolBar.setObjectName(_fromUtf8("menutoolBar"))
        FlowsMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.menutoolBar)
        self.actionClose_Image = QtGui.QAction(FlowsMainWindow)
        self.actionClose_Image.setObjectName(_fromUtf8("actionClose_Image"))
        self.actionQuit = QtGui.QAction(FlowsMainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionFlows = QtGui.QAction(FlowsMainWindow)
        self.actionFlows.setObjectName(_fromUtf8("actionFlows"))
        self.actionHistogram = QtGui.QAction(FlowsMainWindow)
        self.actionHistogram.setObjectName(_fromUtf8("actionHistogram"))
        self.actionDivergences = QtGui.QAction(FlowsMainWindow)
        self.actionDivergences.setObjectName(_fromUtf8("actionDivergences"))
        self.actionOverlays = QtGui.QAction(FlowsMainWindow)
        self.actionOverlays.setObjectName(_fromUtf8("actionOverlays"))
        self.actionAbot = QtGui.QAction(FlowsMainWindow)
        self.actionAbot.setObjectName(_fromUtf8("actionAbot"))
        self.actionDocumentation = QtGui.QAction(FlowsMainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionSave = QtGui.QAction(FlowsMainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLasso = QtGui.QAction(FlowsMainWindow)
        self.actionLasso.setObjectName(_fromUtf8("actionLasso"))
        self.actionOpen_Cube = QtGui.QAction(FlowsMainWindow)
        self.actionOpen_Cube.setObjectName(_fromUtf8("actionOpen_Cube"))
        self.actionOpen_Context_Image = QtGui.QAction(FlowsMainWindow)
        self.actionOpen_Context_Image.setObjectName(_fromUtf8("actionOpen_Context_Image"))
        self.actionMultiDim = QtGui.QAction(FlowsMainWindow)
        self.actionMultiDim.setObjectName(_fromUtf8("actionMultiDim"))
        self.actionNothing = QtGui.QAction(FlowsMainWindow)
        self.actionNothing.setObjectName(_fromUtf8("actionNothing"))
        self.actionOpenCube = QtGui.QAction(FlowsMainWindow)
        self.actionOpenCube.setObjectName(_fromUtf8("actionOpenCube"))
        self.menuFile.addAction(self.actionOpenCube)
        self.menuFile.addAction(self.actionClose_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuOperation.addAction(self.actionFlows)
        self.menuOperation.addAction(self.actionHistogram)
        self.menuOperation.addAction(self.actionDivergences)
        self.menuOperation.addAction(self.actionOverlays)
        self.menuOperation.addAction(self.actionLasso)
        self.menuOperation.addAction(self.actionMultiDim)
        self.menuHelp.addAction(self.actionAbot)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FlowsMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.ImagetabWidget_2.setCurrentIndex(0)
        self.MDToolstabWidget_2.setCurrentIndex(1)
        self.ImProptabWidget_2.setCurrentIndex(2)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.nslice_label_8.setNum)
        QtCore.QObject.connect(self.AmplificatorSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.Amplificatorlabel.setNum)
        QtCore.QObject.connect(self.horizontalSliderLow, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.numLowlabel.setNum)
        QtCore.QObject.connect(self.horizontalSliderHigh, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.numHighlabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(FlowsMainWindow)

    def retranslateUi(self, FlowsMainWindow):
        FlowsMainWindow.setWindowTitle(_translate("FlowsMainWindow", "Vector Velocities with Sunpy", None))
        self.contextlabel.setText(_translate("FlowsMainWindow", "Context Image", None))
        self.InfoplainTextEdit.setPlainText(_translate("FlowsMainWindow", "Name : None\n"
"X : \n"
"Y :\n"
"Value : \n"
"Dimensions : \n"
"Min : \n"
"Max :\n"
"Pixel Size :\n"
"Temporal cadence :\n"
"\n"
"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Infotab), _translate("FlowsMainWindow", "Info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FlowsMainWindow", "Header", None))
        self.ImagetabWidget_2.setTabText(self.ImagetabWidget_2.indexOf(self.image), _translate("FlowsMainWindow", "Image", None))
        self.axes_label_8.setText(_translate("FlowsMainWindow", "Axes units:", None))
        self.arcradioButton.setText(_translate("FlowsMainWindow", "Arcseconds", None))
        self.meter_radioButton_2.setText(_translate("FlowsMainWindow", "Mm", None))
        self.RestorepushButton_2.setText(_translate("FlowsMainWindow", "Redraw", None))
        self.Message.setText(_translate("FlowsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">In this workspace will be open </span></p><p align=\"center\"><span style=\" font-size:24pt;\">the avalaible operations</span></p><p align=\"center\"><br/></p></body></html>", None))
        self.Intruc_flowlabel_2.setText(_translate("FlowsMainWindow", "Instructions", None))
        self.Instru1plainTextEdit.setPlainText(_translate("FlowsMainWindow", "Enter the different parameters to calculate flow vectors field.", None))
        self.Options_CalcgroupBox.setTitle(_translate("FlowsMainWindow", "Options to calculate:", None))
        self.labelTitle.setText(_translate("FlowsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Values for time average</span></p></body></html>", None))
        self.FWHM1_2.setText(_translate("FlowsMainWindow", "FHWM (arcsec per pixel)", None))
        self.Pixelsize_2.setText(_translate("FlowsMainWindow", "Pixel size (arcsec)", None))
        self.label.setText(_translate("FlowsMainWindow", "Cadence (seconds)", None))
        self.labelInit.setText(_translate("FlowsMainWindow", "Initial Image:", None))
        self.labelEnd.setText(_translate("FlowsMainWindow", "Last Image:", None))
        self.vectorOptiongroupBox.setTitle(_translate("FlowsMainWindow", "Vector Options:", None))
        self.Pixel_2.setText(_translate("FlowsMainWindow", "Density of vectors", None))
        self.Color_2.setText(_translate("FlowsMainWindow", "Color", None))
        self.ColorSelector.setText(_translate("FlowsMainWindow", "Color", None))
        self.Pivot_2.setText(_translate("FlowsMainWindow", "Pivot", None))
        self.PivotSelector.setItemText(0, _translate("FlowsMainWindow", "tail", None))
        self.PivotSelector.setItemText(1, _translate("FlowsMainWindow", "middle", None))
        self.PivotSelector.setItemText(2, _translate("FlowsMainWindow", "tip", None))
        self.Width_2.setText(_translate("FlowsMainWindow", "Width", None))
        self.Scale_2.setText(_translate("FlowsMainWindow", "Scale", None))
        self.Units_2.setText(_translate("FlowsMainWindow", "Units", None))
        self.UnitsSelector.setItemText(0, _translate("FlowsMainWindow", "dots", None))
        self.UnitsSelector.setItemText(1, _translate("FlowsMainWindow", "inches", None))
        self.maskPushButton.setText(_translate("FlowsMainWindow", "Mask", None))
        self.fullImageButton.setText(_translate("FlowsMainWindow", "Full Image", None))
        self.pushButton.setText(_translate("FlowsMainWindow", "Calculate", None))
        self.vmasklabel.setText(_translate("FlowsMainWindow", "Velocity Mask", None))
        self.masklabel.setText(_translate("FlowsMainWindow", "Intensity Mask", None))
        self.vminlabel_5.setText(_translate("FlowsMainWindow", "Vmin", None))
        self.vmaxlabel_6.setText(_translate("FlowsMainWindow", "Vmax", None))
        self.iminlabel_7.setText(_translate("FlowsMainWindow", "Imin", None))
        self.imaxlabel_8.setText(_translate("FlowsMainWindow", "Imax", None))
        self.closeButton_1.setText(_translate("FlowsMainWindow", "Close", None))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_3), _translate("FlowsMainWindow", "Flows Tools", None))
        self.SaveHist_pushButton.setText(_translate("FlowsMainWindow", "Save Histogram", None))
        self.closeButton_2.setText(_translate("FlowsMainWindow", "Close", None))
        self.Intruc_histolabel_2.setText(_translate("FlowsMainWindow", "Instructions", None))
        self.histo_plainTextEdit.setPlainText(_translate("FlowsMainWindow", "Draw (or redraw) a region with the left mouse button. Or you can chose some parameter to calculate the histogram.", None))
        self.RegionpushButton_2.setText(_translate("FlowsMainWindow", "Region", None))
        self.fullhistpushButton.setText(_translate("FlowsMainWindow", "Full Image", None))
        self.pixelradioButton.setText(_translate("FlowsMainWindow", "Pixel distribution", None))
        self.velocityradioButton_2.setText(_translate("FlowsMainWindow", "Velocity distribution", None))
        self.checkBoxFit.setText(_translate("FlowsMainWindow", "Plot Fit", None))
        self.LOGcheckBox.setText(_translate("FlowsMainWindow", "Log Histogram", None))
        self.propertiesButton.setText(_translate("FlowsMainWindow", "Plot Tools", None))
        self.fitButton.setText(_translate("FlowsMainWindow", "Fit functions \n"
"Properties", None))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_4), _translate("FlowsMainWindow", "Histogram Tools", None))
        self.diverlabel_5.setText(_translate("FlowsMainWindow", "Instructions", None))
        self.plainTextEdit.setPlainText(_translate("FlowsMainWindow", "Plot the divergences map. You can choose overplot with vectors or contours.", None))
        self.cmaptoolButton.setText(_translate("FlowsMainWindow", "CMAP", None))
        self.label_5.setText(_translate("FlowsMainWindow", "Contrast Low:", None))
        self.label_6.setText(_translate("FlowsMainWindow", "Contrast High", None))
        self.vecradioButton.setText(_translate("FlowsMainWindow", "Vectors", None))
        self.contourradioButton.setText(_translate("FlowsMainWindow", "Contours", None))
        self.plot_diverpushButton.setText(_translate("FlowsMainWindow", "Plot", None))
        self.AmpliTitleLabel.setText(_translate("FlowsMainWindow", "Amplificator", None))
        self.Amplificatorlabel.setText(_translate("FlowsMainWindow", "1", None))
        self.alphaTitleLabel.setText(_translate("FlowsMainWindow", "Opacity", None))
        self.alphalineEdit.setText(_translate("FlowsMainWindow", "1.0", None))
        self.ImProptabWidget_2.setTabText(self.ImProptabWidget_2.indexOf(self.tab_8), _translate("FlowsMainWindow", "Image Properties", None))
        self.Pixel_4.setText(_translate("FlowsMainWindow", "Density of vectors", None))
        self.Color_4.setText(_translate("FlowsMainWindow", "Color", None))
        self.ColorSelector_2.setText(_translate("FlowsMainWindow", "Color", None))
        self.Pivot_4.setText(_translate("FlowsMainWindow", "Pivot", None))
        self.PivotSelector_2.setItemText(0, _translate("FlowsMainWindow", "tail", None))
        self.PivotSelector_2.setItemText(1, _translate("FlowsMainWindow", "middle", None))
        self.PivotSelector_2.setItemText(2, _translate("FlowsMainWindow", "tip", None))
        self.Width_4.setText(_translate("FlowsMainWindow", "Width", None))
        self.Scale_4.setText(_translate("FlowsMainWindow", "Scale", None))
        self.Units_4.setText(_translate("FlowsMainWindow", "Units", None))
        self.UnitsSelector_2.setItemText(0, _translate("FlowsMainWindow", "dots", None))
        self.UnitsSelector_2.setItemText(1, _translate("FlowsMainWindow", "inches", None))
        self.ImProptabWidget_2.setTabText(self.ImProptabWidget_2.indexOf(self.tab_9), _translate("FlowsMainWindow", "Vector Properties", None))
        self.CMAP_contourtoolButton.setText(_translate("FlowsMainWindow", "CMAP", None))
        self.LevelgroupBox.setTitle(_translate("FlowsMainWindow", "Levels", None))
        self.l1_radioButton.setText(_translate("FlowsMainWindow", "Single Value", None))
        self.l2_radioButton_2.setText(_translate("FlowsMainWindow", "List Values", None))
        self.l3_radioButton_3.setText(_translate("FlowsMainWindow", "Range Values", None))
        self.sc_lineEdit_7.setText(_translate("FlowsMainWindow", "10", None))
        self.lineEdit_8.setPlaceholderText(_translate("FlowsMainWindow", "e. g. 10,13,16,..", None))
        self.lineEdit_9.setPlaceholderText(_translate("FlowsMainWindow", "e. g. start,end, npartitions", None))
        self.label_7.setText(_translate("FlowsMainWindow", "Alpha", None))
        self.vaminlabel_8.setText(_translate("FlowsMainWindow", "Value Min", None))
        self.vamaxlabel_8.setText(_translate("FlowsMainWindow", "Value Max", None))
        self.originlabel_8.setText(_translate("FlowsMainWindow", "Origin", None))
        self.lineEdit_6.setPlaceholderText(_translate("FlowsMainWindow", "None | upper | lower | image", None))
        self.closeButton_3.setText(_translate("FlowsMainWindow", "Close", None))
        self.ImProptabWidget_2.setTabText(self.ImProptabWidget_2.indexOf(self.tab_10), _translate("FlowsMainWindow", "Countours Properties", None))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_5), _translate("FlowsMainWindow", "Divergences Tools", None))
        self.Instruc_overlabel_8.setText(_translate("FlowsMainWindow", "Instructions", None))
        self.overplainTextEdit_2.setPlainText(_translate("FlowsMainWindow", "Enter the limits for saturation.", None))
        self.limgroupBox.setTitle(_translate("FlowsMainWindow", "Overlay", None))
        self.OverlaypushButton_4.setText(_translate("FlowsMainWindow", "Overlay", None))
        self.alfalabel_8.setText(_translate("FlowsMainWindow", "alpha", None))
        self.lowcollabel_9.setText(_translate("FlowsMainWindow", "Low Color", None))
        self.chooselow_pushButton_2.setText(_translate("FlowsMainWindow", "Choose Color", None))
        self.lowlim_label_10.setText(_translate("FlowsMainWindow", "Low Limit", None))
        self.hicollabel_11.setText(_translate("FlowsMainWindow", "High Color", None))
        self.hicolpushButton_3.setText(_translate("FlowsMainWindow", "Choose Color", None))
        self.hilim_label_12.setText(_translate("FlowsMainWindow", "High Limit", None))
        self.closeButton_4.setText(_translate("FlowsMainWindow", "Close", None))
        self.ContrastTitle.setText(_translate("FlowsMainWindow", "Contrast Tool", None))
        self.CutLowlabel.setText(_translate("FlowsMainWindow", "Cut Low", None))
        self.CutHighlabel.setText(_translate("FlowsMainWindow", "Cut High", None))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_6), _translate("FlowsMainWindow", "Overlays Tools", None))
        self.plainTextEdit_2.setPlainText(_translate("FlowsMainWindow", "With this option you can select ans specific mask and erase vectors of selected region.", None))
        self.start_lassoButton.setText(_translate("FlowsMainWindow", "Start", None))
        self.stop_lassoButton.setText(_translate("FlowsMainWindow", "Stop", None))
        self.label_8.setText(_translate("FlowsMainWindow", "Statistics", None))
        self.LassoMaskpushButton.setText(_translate("FlowsMainWindow", "Make Mask", None))
        self.closeButton_5.setText(_translate("FlowsMainWindow", "Close", None))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab), _translate("FlowsMainWindow", "Lasso", None))
        self.instruc_md_label_8.setText(_translate("FlowsMainWindow", "Instructions", None))
        self.Instruc_md_plainTextEdit_2.setPlainText(_translate("FlowsMainWindow", "Use control buttons to move through the movie. (Cube Data)", None))
        self.hdu_label_8.setText(_translate("FlowsMainWindow", "HDU", None))
        self.naxis_label_8.setText(_translate("FlowsMainWindow", "NAXIS (Data Cube)", None))
        self.na1_label_8.setText(_translate("FlowsMainWindow", "NAXIS 1", None))
        self.na2_label_9.setText(_translate("FlowsMainWindow", "NAXIS 2", None))
        self.na3_label_10.setText(_translate("FlowsMainWindow", "NAXIS 3", None))
        self.slice_label_8.setText(_translate("FlowsMainWindow", "Slice:", None))
        self.framelabel_8.setText(_translate("FlowsMainWindow", "Num. Frames/sec:", None))
        self.firstpushButton_2.setText(_translate("FlowsMainWindow", "First", None))
        self.prev_pushButton_3.setText(_translate("FlowsMainWindow", "Previous", None))
        self.stoppushButton_4.setText(_translate("FlowsMainWindow", "Stop", None))
        self.endpushButton_5.setText(_translate("FlowsMainWindow", "End", None))
        self.nextpushButton_6.setText(_translate("FlowsMainWindow", "Next", None))
        self.playpushButton_7.setText(_translate("FlowsMainWindow", "Play", None))
        self.closeButton_6.setText(_translate("FlowsMainWindow", "Close", None))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_7), _translate("FlowsMainWindow", "MultiDim", None))
        self.zoomgroupBox.setTitle(_translate("FlowsMainWindow", "Zooming region", None))
        self.xinf_label.setText(_translate("FlowsMainWindow", "xinf", None))
        self.yinf_label_2.setText(_translate("FlowsMainWindow", "yinf", None))
        self.xsup_label_3.setText(_translate("FlowsMainWindow", "xsup", None))
        self.ysup_label_4.setText(_translate("FlowsMainWindow", "ysup", None))
        self.PlotRegionpushButton.setText(_translate("FlowsMainWindow", "Resize Window", None))
        self.menuFile.setTitle(_translate("FlowsMainWindow", "File", None))
        self.menuOperation.setTitle(_translate("FlowsMainWindow", "Operation", None))
        self.menuHelp.setTitle(_translate("FlowsMainWindow", "Help", None))
        self.menutoolBar.setWindowTitle(_translate("FlowsMainWindow", "toolBar", None))
        self.actionClose_Image.setText(_translate("FlowsMainWindow", "Close", None))
        self.actionQuit.setText(_translate("FlowsMainWindow", "Quit", None))
        self.actionFlows.setText(_translate("FlowsMainWindow", "Flows", None))
        self.actionHistogram.setText(_translate("FlowsMainWindow", "Histogram", None))
        self.actionDivergences.setText(_translate("FlowsMainWindow", "Divergences", None))
        self.actionOverlays.setText(_translate("FlowsMainWindow", "Overlays", None))
        self.actionAbot.setText(_translate("FlowsMainWindow", "Abot", None))
        self.actionDocumentation.setText(_translate("FlowsMainWindow", "Documentation", None))
        self.actionSave.setText(_translate("FlowsMainWindow", "Save", None))
        self.actionLasso.setText(_translate("FlowsMainWindow", "Lasso", None))
        self.actionOpen_Cube.setText(_translate("FlowsMainWindow", "Open Cube", None))
        self.actionOpen_Context_Image.setText(_translate("FlowsMainWindow", "Open Context Image", None))
        self.actionMultiDim.setText(_translate("FlowsMainWindow", "MultiDim", None))
        self.actionNothing.setText(_translate("FlowsMainWindow", "Nothing", None))
        self.actionOpenCube.setText(_translate("FlowsMainWindow", "Open Cube", None))

