# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vector_Velocities_with_Sunpy.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlowsMainWindow(object):
    def setupUi(self, FlowsMainWindow):
        FlowsMainWindow.setObjectName("FlowsMainWindow")
        FlowsMainWindow.resize(1421, 814)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlowsMainWindow.sizePolicy().hasHeightForWidth())
        FlowsMainWindow.setSizePolicy(sizePolicy)
        FlowsMainWindow.setIconSize(QtCore.QSize(1, 1))
        FlowsMainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(FlowsMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1120, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1420, 846))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 301, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.Infotab = QtWidgets.QWidget()
        self.Infotab.setObjectName("Infotab")
        self.layoutWidget = QtWidgets.QWidget(self.Infotab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 291, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_8.addWidget(self.widget)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.contextlabel = QtWidgets.QLabel(self.layoutWidget)
        self.contextlabel.setObjectName("contextlabel")
        self.horizontalLayout_15.addWidget(self.contextlabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.InfoplainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoplainTextEdit.sizePolicy().hasHeightForWidth())
        self.InfoplainTextEdit.setSizePolicy(sizePolicy)
        self.InfoplainTextEdit.setReadOnly(True)
        self.InfoplainTextEdit.setObjectName("InfoplainTextEdit")
        self.verticalLayout_8.addWidget(self.InfoplainTextEdit)
        self.tabWidget.addTab(self.Infotab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.HeadertableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.HeadertableWidget.setGeometry(QtCore.QRect(0, 0, 291, 591))
        self.HeadertableWidget.setObjectName("HeadertableWidget")
        self.HeadertableWidget.setColumnCount(0)
        self.HeadertableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.ImagetabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.ImagetabWidget_2.setGeometry(QtCore.QRect(320, 10, 711, 671))
        self.ImagetabWidget_2.setObjectName("ImagetabWidget_2")
        self.image = QtWidgets.QWidget()
        self.image.setObjectName("image")
        self.layoutWidget1 = QtWidgets.QWidget(self.image)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 701, 631))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ToolBar_widget_3 = QtWidgets.QWidget(self.layoutWidget1)
        self.ToolBar_widget_3.setObjectName("ToolBar_widget_3")
        self.MeanImage_widget_3 = QtWidgets.QWidget(self.ToolBar_widget_3)
        self.MeanImage_widget_3.setGeometry(QtCore.QRect(0, 0, 691, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MeanImage_widget_3.sizePolicy().hasHeightForWidth())
        self.MeanImage_widget_3.setSizePolicy(sizePolicy)
        self.MeanImage_widget_3.setObjectName("MeanImage_widget_3")
        self.verticalLayout_7.addWidget(self.ToolBar_widget_3)
        self.ImagetabWidget_2.addTab(self.image, "")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(640, 700, 253, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.axes_label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.axes_label_8.setObjectName("axes_label_8")
        self.horizontalLayout_8.addWidget(self.axes_label_8)
        self.arcradioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.arcradioButton.setChecked(True)
        self.arcradioButton.setObjectName("arcradioButton")
        self.horizontalLayout_8.addWidget(self.arcradioButton)
        self.meter_radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.meter_radioButton_2.setChecked(False)
        self.meter_radioButton_2.setObjectName("meter_radioButton_2")
        self.horizontalLayout_8.addWidget(self.meter_radioButton_2)
        self.RestorepushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.RestorepushButton_2.setGeometry(QtCore.QRect(920, 700, 85, 26))
        self.RestorepushButton_2.setObjectName("RestorepushButton_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 280, 21, 81))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1030, 270, 21, 81))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Message = QtWidgets.QLabel(self.centralwidget)
        self.Message.setGeometry(QtCore.QRect(1065, 330, 331, 121))
        self.Message.setObjectName("Message")
        self.MDToolstabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.MDToolstabWidget_2.setGeometry(QtCore.QRect(1040, 10, 371, 771))
        self.MDToolstabWidget_2.setTabsClosable(False)
        self.MDToolstabWidget_2.setMovable(False)
        self.MDToolstabWidget_2.setObjectName("MDToolstabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Intruc_flowlabel_2 = QtWidgets.QLabel(self.tab_3)
        self.Intruc_flowlabel_2.setGeometry(QtCore.QRect(100, 0, 81, 21))
        self.Intruc_flowlabel_2.setObjectName("Intruc_flowlabel_2")
        self.Instru1plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.Instru1plainTextEdit.setGeometry(QtCore.QRect(20, 20, 321, 41))
        self.Instru1plainTextEdit.setReadOnly(True)
        self.Instru1plainTextEdit.setObjectName("Instru1plainTextEdit")
        self.Options_CalcgroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.Options_CalcgroupBox.setGeometry(QtCore.QRect(10, 70, 341, 221))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setUnderline(False)
        self.Options_CalcgroupBox.setFont(font)
        self.Options_CalcgroupBox.setObjectName("Options_CalcgroupBox")
        self.labelTitle = QtWidgets.QLabel(self.Options_CalcgroupBox)
        self.labelTitle.setGeometry(QtCore.QRect(100, 130, 131, 31))
        self.labelTitle.setObjectName("labelTitle")
        self.layoutWidget3 = QtWidgets.QWidget(self.Options_CalcgroupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 20, 218, 111))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FWHM1_2 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWHM1_2.sizePolicy().hasHeightForWidth())
        self.FWHM1_2.setSizePolicy(sizePolicy)
        self.FWHM1_2.setObjectName("FWHM1_2")
        self.horizontalLayout.addWidget(self.FWHM1_2)
        self.FWHMSelector = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.FWHMSelector.setProperty("value", 3.0)
        self.FWHMSelector.setObjectName("FWHMSelector")
        self.horizontalLayout.addWidget(self.FWHMSelector)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Pixelsize = QtWidgets.QHBoxLayout()
        self.Pixelsize.setObjectName("Pixelsize")
        self.Pixelsize_2 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pixelsize_2.sizePolicy().hasHeightForWidth())
        self.Pixelsize_2.setSizePolicy(sizePolicy)
        self.Pixelsize_2.setObjectName("Pixelsize_2")
        self.Pixelsize.addWidget(self.Pixelsize_2)
        self.PixelsizeSelector = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PixelsizeSelector.sizePolicy().hasHeightForWidth())
        self.PixelsizeSelector.setSizePolicy(sizePolicy)
        self.PixelsizeSelector.setDecimals(3)
        self.PixelsizeSelector.setProperty("value", 0.5)
        self.PixelsizeSelector.setObjectName("PixelsizeSelector")
        self.Pixelsize.addWidget(self.PixelsizeSelector)
        self.verticalLayout.addLayout(self.Pixelsize)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.CadenceSelector = QtWidgets.QSpinBox(self.layoutWidget3)
        self.CadenceSelector.setMaximum(100000)
        self.CadenceSelector.setProperty("value", 45)
        self.CadenceSelector.setObjectName("CadenceSelector")
        self.horizontalLayout_2.addWidget(self.CadenceSelector)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget4 = QtWidgets.QWidget(self.Options_CalcgroupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 160, 321, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.labelInit = QtWidgets.QLabel(self.layoutWidget4)
        self.labelInit.setObjectName("labelInit")
        self.horizontalLayout_34.addWidget(self.labelInit)
        self.spinBoxInit = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBoxInit.setMaximum(999)
        self.spinBoxInit.setObjectName("spinBoxInit")
        self.horizontalLayout_34.addWidget(self.spinBoxInit)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.labelEnd = QtWidgets.QLabel(self.layoutWidget4)
        self.labelEnd.setObjectName("labelEnd")
        self.horizontalLayout_35.addWidget(self.labelEnd)
        self.spinBoxEnd = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBoxEnd.setMaximum(999)
        self.spinBoxEnd.setProperty("value", 20)
        self.spinBoxEnd.setObjectName("spinBoxEnd")
        self.horizontalLayout_35.addWidget(self.spinBoxEnd)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_35)
        self.vectorOptiongroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.vectorOptiongroupBox.setGeometry(QtCore.QRect(10, 330, 341, 261))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setUnderline(False)
        self.vectorOptiongroupBox.setFont(font)
        self.vectorOptiongroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.vectorOptiongroupBox.setObjectName("vectorOptiongroupBox")
        self.layoutWidget5 = QtWidgets.QWidget(self.vectorOptiongroupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 321, 231))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Pixel = QtWidgets.QHBoxLayout()
        self.Pixel.setObjectName("Pixel")
        self.Pixel_2 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pixel_2.sizePolicy().hasHeightForWidth())
        self.Pixel_2.setSizePolicy(sizePolicy)
        self.Pixel_2.setObjectName("Pixel_2")
        self.Pixel.addWidget(self.Pixel_2)
        self.PixelSelector = QtWidgets.QSpinBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PixelSelector.sizePolicy().hasHeightForWidth())
        self.PixelSelector.setSizePolicy(sizePolicy)
        self.PixelSelector.setProperty("value", 10)
        self.PixelSelector.setObjectName("PixelSelector")
        self.Pixel.addWidget(self.PixelSelector)
        self.verticalLayout_2.addLayout(self.Pixel)
        self.Color = QtWidgets.QHBoxLayout()
        self.Color.setObjectName("Color")
        self.Color_2 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color_2.sizePolicy().hasHeightForWidth())
        self.Color_2.setSizePolicy(sizePolicy)
        self.Color_2.setObjectName("Color_2")
        self.Color.addWidget(self.Color_2)
        self.ColorSelector = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorSelector.sizePolicy().hasHeightForWidth())
        self.ColorSelector.setSizePolicy(sizePolicy)
        self.ColorSelector.setObjectName("ColorSelector")
        self.Color.addWidget(self.ColorSelector)
        self.verticalLayout_2.addLayout(self.Color)
        self.Pivot = QtWidgets.QHBoxLayout()
        self.Pivot.setObjectName("Pivot")
        self.Pivot_2 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pivot_2.sizePolicy().hasHeightForWidth())
        self.Pivot_2.setSizePolicy(sizePolicy)
        self.Pivot_2.setObjectName("Pivot_2")
        self.Pivot.addWidget(self.Pivot_2)
        self.PivotSelector = QtWidgets.QComboBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PivotSelector.sizePolicy().hasHeightForWidth())
        self.PivotSelector.setSizePolicy(sizePolicy)
        self.PivotSelector.setObjectName("PivotSelector")
        self.PivotSelector.addItem("")
        self.PivotSelector.addItem("")
        self.PivotSelector.addItem("")
        self.Pivot.addWidget(self.PivotSelector)
        self.verticalLayout_2.addLayout(self.Pivot)
        self.Width = QtWidgets.QHBoxLayout()
        self.Width.setObjectName("Width")
        self.Width_2 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Width_2.sizePolicy().hasHeightForWidth())
        self.Width_2.setSizePolicy(sizePolicy)
        self.Width_2.setObjectName("Width_2")
        self.Width.addWidget(self.Width_2)
        self.WidthSelector = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidthSelector.sizePolicy().hasHeightForWidth())
        self.WidthSelector.setSizePolicy(sizePolicy)
        self.WidthSelector.setDecimals(6)
        self.WidthSelector.setMinimum(1e-05)
        self.WidthSelector.setSingleStep(0.01)
        self.WidthSelector.setProperty("value", 1.5)
        self.WidthSelector.setObjectName("WidthSelector")
        self.Width.addWidget(self.WidthSelector)
        self.verticalLayout_2.addLayout(self.Width)
        self.Scale = QtWidgets.QHBoxLayout()
        self.Scale.setObjectName("Scale")
        self.Scale_2 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale_2.sizePolicy().hasHeightForWidth())
        self.Scale_2.setSizePolicy(sizePolicy)
        self.Scale_2.setObjectName("Scale_2")
        self.Scale.addWidget(self.Scale_2)
        self.ScaleSelector = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleSelector.sizePolicy().hasHeightForWidth())
        self.ScaleSelector.setSizePolicy(sizePolicy)
        self.ScaleSelector.setDecimals(4)
        self.ScaleSelector.setProperty("value", 0.17)
        self.ScaleSelector.setObjectName("ScaleSelector")
        self.Scale.addWidget(self.ScaleSelector)
        self.verticalLayout_2.addLayout(self.Scale)
        self.Units = QtWidgets.QHBoxLayout()
        self.Units.setObjectName("Units")
        self.Units_2 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units_2.sizePolicy().hasHeightForWidth())
        self.Units_2.setSizePolicy(sizePolicy)
        self.Units_2.setObjectName("Units_2")
        self.Units.addWidget(self.Units_2)
        self.UnitsSelector = QtWidgets.QComboBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnitsSelector.sizePolicy().hasHeightForWidth())
        self.UnitsSelector.setSizePolicy(sizePolicy)
        self.UnitsSelector.setObjectName("UnitsSelector")
        self.UnitsSelector.addItem("")
        self.UnitsSelector.addItem("")
        self.Units.addWidget(self.UnitsSelector)
        self.verticalLayout_2.addLayout(self.Units)
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(70, 677, 221, 32))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.PlotClear = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.PlotClear.setContentsMargins(0, 0, 0, 0)
        self.PlotClear.setObjectName("PlotClear")
        self.maskPushButton = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskPushButton.sizePolicy().hasHeightForWidth())
        self.maskPushButton.setSizePolicy(sizePolicy)
        self.maskPushButton.setObjectName("maskPushButton")
        self.PlotClear.addWidget(self.maskPushButton)
        self.fullImageButton = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullImageButton.sizePolicy().hasHeightForWidth())
        self.fullImageButton.setSizePolicy(sizePolicy)
        self.fullImageButton.setObjectName("fullImageButton")
        self.PlotClear.addWidget(self.fullImageButton)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(270, 300, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.vmasklabel = QtWidgets.QLabel(self.tab_3)
        self.vmasklabel.setGeometry(QtCore.QRect(60, 590, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.vmasklabel.setFont(font)
        self.vmasklabel.setObjectName("vmasklabel")
        self.masklabel = QtWidgets.QLabel(self.tab_3)
        self.masklabel.setGeometry(QtCore.QRect(210, 587, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.masklabel.setFont(font)
        self.masklabel.setObjectName("masklabel")
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(50, 610, 111, 62))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.vminlabel_5 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(10)
        self.vminlabel_5.setFont(font)
        self.vminlabel_5.setObjectName("vminlabel_5")
        self.horizontalLayout_23.addWidget(self.vminlabel_5)
        self.vminlineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        self.vminlineEdit.setObjectName("vminlineEdit")
        self.horizontalLayout_23.addWidget(self.vminlineEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.vmaxlabel_6 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(10)
        self.vmaxlabel_6.setFont(font)
        self.vmaxlabel_6.setObjectName("vmaxlabel_6")
        self.horizontalLayout_25.addWidget(self.vmaxlabel_6)
        self.vmaxlineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        self.vmaxlineEdit.setObjectName("vmaxlineEdit")
        self.horizontalLayout_25.addWidget(self.vmaxlineEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.layoutWidget8 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(200, 610, 101, 62))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.iminlabel_7 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(10)
        self.iminlabel_7.setFont(font)
        self.iminlabel_7.setObjectName("iminlabel_7")
        self.horizontalLayout_24.addWidget(self.iminlabel_7)
        self.iminlineEdit = QtWidgets.QLineEdit(self.layoutWidget8)
        self.iminlineEdit.setObjectName("iminlineEdit")
        self.horizontalLayout_24.addWidget(self.iminlineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.imaxlabel_8 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(10)
        self.imaxlabel_8.setFont(font)
        self.imaxlabel_8.setObjectName("imaxlabel_8")
        self.horizontalLayout_26.addWidget(self.imaxlabel_8)
        self.imaxlineEdit = QtWidgets.QLineEdit(self.layoutWidget8)
        self.imaxlineEdit.setObjectName("imaxlineEdit")
        self.horizontalLayout_26.addWidget(self.imaxlineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.closeButton_1 = QtWidgets.QPushButton(self.tab_3)
        self.closeButton_1.setGeometry(QtCore.QRect(290, 720, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closeButton_1.setFont(font)
        self.closeButton_1.setObjectName("closeButton_1")
        self.MDToolstabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.SaveHist_pushButton = QtWidgets.QPushButton(self.tab_4)
        self.SaveHist_pushButton.setGeometry(QtCore.QRect(10, 700, 121, 32))
        self.SaveHist_pushButton.setObjectName("SaveHist_pushButton")
        self.closeButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.closeButton_2.setGeometry(QtCore.QRect(250, 700, 110, 32))
        self.closeButton_2.setObjectName("closeButton_2")
        self.layoutWidget9 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget9.setGeometry(QtCore.QRect(1, 1, 361, 691))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.histoverticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.histoverticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.histoverticalLayout_12.setObjectName("histoverticalLayout_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.Intruc_histolabel_2 = QtWidgets.QLabel(self.layoutWidget9)
        self.Intruc_histolabel_2.setObjectName("Intruc_histolabel_2")
        self.horizontalLayout_20.addWidget(self.Intruc_histolabel_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.histo_plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histo_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.histo_plainTextEdit.setSizePolicy(sizePolicy)
        self.histo_plainTextEdit.setMinimumSize(QtCore.QSize(0, 70))
        self.histo_plainTextEdit.setMaximumSize(QtCore.QSize(256, 70))
        self.histo_plainTextEdit.setReadOnly(True)
        self.histo_plainTextEdit.setObjectName("histo_plainTextEdit")
        self.verticalLayout_9.addWidget(self.histo_plainTextEdit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.histoverticalLayout_12.addLayout(self.verticalLayout_9)
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.histoverticalLayout_12.addWidget(self.widget_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.RegionpushButton_2 = QtWidgets.QPushButton(self.layoutWidget9)
        self.RegionpushButton_2.setObjectName("RegionpushButton_2")
        self.horizontalLayout_12.addWidget(self.RegionpushButton_2)
        self.fullhistpushButton = QtWidgets.QPushButton(self.layoutWidget9)
        self.fullhistpushButton.setObjectName("fullhistpushButton")
        self.horizontalLayout_12.addWidget(self.fullhistpushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pixelradioButton = QtWidgets.QRadioButton(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.pixelradioButton.setFont(font)
        self.pixelradioButton.setChecked(True)
        self.pixelradioButton.setObjectName("pixelradioButton")
        self.horizontalLayout_16.addWidget(self.pixelradioButton)
        self.velocityradioButton_2 = QtWidgets.QRadioButton(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityradioButton_2.sizePolicy().hasHeightForWidth())
        self.velocityradioButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.velocityradioButton_2.setFont(font)
        self.velocityradioButton_2.setObjectName("velocityradioButton_2")
        self.horizontalLayout_16.addWidget(self.velocityradioButton_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBoxFit = QtWidgets.QCheckBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.checkBoxFit.setFont(font)
        self.checkBoxFit.setObjectName("checkBoxFit")
        self.horizontalLayout_17.addWidget(self.checkBoxFit)
        self.LOGcheckBox = QtWidgets.QCheckBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.LOGcheckBox.setFont(font)
        self.LOGcheckBox.setObjectName("LOGcheckBox")
        self.horizontalLayout_17.addWidget(self.LOGcheckBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.propertiesButton = QtWidgets.QPushButton(self.layoutWidget9)
        self.propertiesButton.setObjectName("propertiesButton")
        self.horizontalLayout_21.addWidget(self.propertiesButton)
        self.fitButton = QtWidgets.QPushButton(self.layoutWidget9)
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout_21.addWidget(self.fitButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.histoverticalLayout_12.addLayout(self.verticalLayout_10)
        self.MDToolstabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.diverlabel_5 = QtWidgets.QLabel(self.tab_5)
        self.diverlabel_5.setGeometry(QtCore.QRect(140, 0, 81, 16))
        self.diverlabel_5.setObjectName("diverlabel_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_5)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 20, 251, 51))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.ImProptabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.ImProptabWidget_2.setGeometry(QtCore.QRect(10, 90, 351, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImProptabWidget_2.sizePolicy().hasHeightForWidth())
        self.ImProptabWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Amiri Quran")
        font.setPointSize(8)
        self.ImProptabWidget_2.setFont(font)
        self.ImProptabWidget_2.setTabsClosable(True)
        self.ImProptabWidget_2.setObjectName("ImProptabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.cmaptoolButton = QtWidgets.QToolButton(self.tab_8)
        self.cmaptoolButton.setGeometry(QtCore.QRect(110, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.cmaptoolButton.setFont(font)
        self.cmaptoolButton.setObjectName("cmaptoolButton")
        self.layoutWidget10 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget10.setGeometry(QtCore.QRect(30, 60, 251, 86))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily("Amiri Quran")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily("Amiri Quran")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.layoutWidget11 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget11.setGeometry(QtCore.QRect(80, 350, 181, 81))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.vecradioButton = QtWidgets.QRadioButton(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vecradioButton.setFont(font)
        self.vecradioButton.setChecked(True)
        self.vecradioButton.setObjectName("vecradioButton")
        self.horizontalLayout_13.addWidget(self.vecradioButton)
        self.contourradioButton = QtWidgets.QRadioButton(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contourradioButton.setFont(font)
        self.contourradioButton.setObjectName("contourradioButton")
        self.horizontalLayout_13.addWidget(self.contourradioButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.plot_diverpushButton = QtWidgets.QPushButton(self.layoutWidget11)
        self.plot_diverpushButton.setObjectName("plot_diverpushButton")
        self.horizontalLayout_14.addWidget(self.plot_diverpushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.AmpliTitleLabel = QtWidgets.QLabel(self.tab_8)
        self.AmpliTitleLabel.setGeometry(QtCore.QRect(90, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(12)
        self.AmpliTitleLabel.setFont(font)
        self.AmpliTitleLabel.setObjectName("AmpliTitleLabel")
        self.layoutWidget12 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget12.setGeometry(QtCore.QRect(50, 180, 221, 41))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.AmplificatorSlider = QtWidgets.QSlider(self.layoutWidget12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AmplificatorSlider.sizePolicy().hasHeightForWidth())
        self.AmplificatorSlider.setSizePolicy(sizePolicy)
        self.AmplificatorSlider.setMinimum(1)
        self.AmplificatorSlider.setMaximum(500)
        self.AmplificatorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AmplificatorSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.AmplificatorSlider.setTickInterval(50)
        self.AmplificatorSlider.setObjectName("AmplificatorSlider")
        self.horizontalLayout_32.addWidget(self.AmplificatorSlider)
        spacerItem7 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem7)
        self.Amplificatorlabel = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Amplificatorlabel.setFont(font)
        self.Amplificatorlabel.setObjectName("Amplificatorlabel")
        self.horizontalLayout_32.addWidget(self.Amplificatorlabel)
        self.layoutWidget13 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget13.setGeometry(QtCore.QRect(90, 240, 151, 41))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.alphaTitleLabel = QtWidgets.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(12)
        self.alphaTitleLabel.setFont(font)
        self.alphaTitleLabel.setObjectName("alphaTitleLabel")
        self.horizontalLayout_33.addWidget(self.alphaTitleLabel)
        self.alphalineEdit = QtWidgets.QLineEdit(self.layoutWidget13)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(12)
        self.alphalineEdit.setFont(font)
        self.alphalineEdit.setObjectName("alphalineEdit")
        self.horizontalLayout_33.addWidget(self.alphalineEdit)
        self.ImProptabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.layoutWidget14 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget14.setGeometry(QtCore.QRect(70, 70, 221, 296))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Pixel_3 = QtWidgets.QHBoxLayout()
        self.Pixel_3.setObjectName("Pixel_3")
        self.Pixel_4 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pixel_4.sizePolicy().hasHeightForWidth())
        self.Pixel_4.setSizePolicy(sizePolicy)
        self.Pixel_4.setObjectName("Pixel_4")
        self.Pixel_3.addWidget(self.Pixel_4)
        self.PixelSelector_2 = QtWidgets.QSpinBox(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PixelSelector_2.sizePolicy().hasHeightForWidth())
        self.PixelSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PixelSelector_2.setFont(font)
        self.PixelSelector_2.setProperty("value", 10)
        self.PixelSelector_2.setObjectName("PixelSelector_2")
        self.Pixel_3.addWidget(self.PixelSelector_2)
        self.verticalLayout_4.addLayout(self.Pixel_3)
        self.Color_3 = QtWidgets.QHBoxLayout()
        self.Color_3.setObjectName("Color_3")
        self.Color_4 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Color_4.sizePolicy().hasHeightForWidth())
        self.Color_4.setSizePolicy(sizePolicy)
        self.Color_4.setObjectName("Color_4")
        self.Color_3.addWidget(self.Color_4)
        self.ColorSelector_2 = QtWidgets.QPushButton(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorSelector_2.sizePolicy().hasHeightForWidth())
        self.ColorSelector_2.setSizePolicy(sizePolicy)
        self.ColorSelector_2.setObjectName("ColorSelector_2")
        self.Color_3.addWidget(self.ColorSelector_2)
        self.verticalLayout_4.addLayout(self.Color_3)
        self.Pivot_3 = QtWidgets.QHBoxLayout()
        self.Pivot_3.setObjectName("Pivot_3")
        self.Pivot_4 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pivot_4.sizePolicy().hasHeightForWidth())
        self.Pivot_4.setSizePolicy(sizePolicy)
        self.Pivot_4.setObjectName("Pivot_4")
        self.Pivot_3.addWidget(self.Pivot_4)
        self.PivotSelector_2 = QtWidgets.QComboBox(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PivotSelector_2.sizePolicy().hasHeightForWidth())
        self.PivotSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PivotSelector_2.setFont(font)
        self.PivotSelector_2.setObjectName("PivotSelector_2")
        self.PivotSelector_2.addItem("")
        self.PivotSelector_2.addItem("")
        self.PivotSelector_2.addItem("")
        self.Pivot_3.addWidget(self.PivotSelector_2)
        self.verticalLayout_4.addLayout(self.Pivot_3)
        self.Width_3 = QtWidgets.QHBoxLayout()
        self.Width_3.setObjectName("Width_3")
        self.Width_4 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Width_4.sizePolicy().hasHeightForWidth())
        self.Width_4.setSizePolicy(sizePolicy)
        self.Width_4.setObjectName("Width_4")
        self.Width_3.addWidget(self.Width_4)
        self.WidthSelector_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidthSelector_2.sizePolicy().hasHeightForWidth())
        self.WidthSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WidthSelector_2.setFont(font)
        self.WidthSelector_2.setDecimals(6)
        self.WidthSelector_2.setMinimum(1e-05)
        self.WidthSelector_2.setSingleStep(0.01)
        self.WidthSelector_2.setProperty("value", 1.5)
        self.WidthSelector_2.setObjectName("WidthSelector_2")
        self.Width_3.addWidget(self.WidthSelector_2)
        self.verticalLayout_4.addLayout(self.Width_3)
        self.Scale_3 = QtWidgets.QHBoxLayout()
        self.Scale_3.setObjectName("Scale_3")
        self.Scale_4 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale_4.sizePolicy().hasHeightForWidth())
        self.Scale_4.setSizePolicy(sizePolicy)
        self.Scale_4.setObjectName("Scale_4")
        self.Scale_3.addWidget(self.Scale_4)
        self.ScaleSelector_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleSelector_2.sizePolicy().hasHeightForWidth())
        self.ScaleSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScaleSelector_2.setFont(font)
        self.ScaleSelector_2.setDecimals(4)
        self.ScaleSelector_2.setProperty("value", 0.17)
        self.ScaleSelector_2.setObjectName("ScaleSelector_2")
        self.Scale_3.addWidget(self.ScaleSelector_2)
        self.verticalLayout_4.addLayout(self.Scale_3)
        self.Units_3 = QtWidgets.QHBoxLayout()
        self.Units_3.setObjectName("Units_3")
        self.Units_4 = QtWidgets.QLabel(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units_4.sizePolicy().hasHeightForWidth())
        self.Units_4.setSizePolicy(sizePolicy)
        self.Units_4.setObjectName("Units_4")
        self.Units_3.addWidget(self.Units_4)
        self.UnitsSelector_2 = QtWidgets.QComboBox(self.layoutWidget14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnitsSelector_2.sizePolicy().hasHeightForWidth())
        self.UnitsSelector_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UnitsSelector_2.setFont(font)
        self.UnitsSelector_2.setObjectName("UnitsSelector_2")
        self.UnitsSelector_2.addItem("")
        self.UnitsSelector_2.addItem("")
        self.Units_3.addWidget(self.UnitsSelector_2)
        self.verticalLayout_4.addLayout(self.Units_3)
        self.ImProptabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.CMAP_contourtoolButton = QtWidgets.QToolButton(self.tab_10)
        self.CMAP_contourtoolButton.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.CMAP_contourtoolButton.setObjectName("CMAP_contourtoolButton")
        self.LevelgroupBox = QtWidgets.QGroupBox(self.tab_10)
        self.LevelgroupBox.setGeometry(QtCore.QRect(20, 310, 301, 191))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.LevelgroupBox.setFont(font)
        self.LevelgroupBox.setObjectName("LevelgroupBox")
        self.l1_radioButton = QtWidgets.QRadioButton(self.LevelgroupBox)
        self.l1_radioButton.setGeometry(QtCore.QRect(0, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1_radioButton.setFont(font)
        self.l1_radioButton.setChecked(True)
        self.l1_radioButton.setObjectName("l1_radioButton")
        self.l2_radioButton_2 = QtWidgets.QRadioButton(self.LevelgroupBox)
        self.l2_radioButton_2.setGeometry(QtCore.QRect(0, 90, 105, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2_radioButton_2.setFont(font)
        self.l2_radioButton_2.setObjectName("l2_radioButton_2")
        self.l3_radioButton_3 = QtWidgets.QRadioButton(self.LevelgroupBox)
        self.l3_radioButton_3.setGeometry(QtCore.QRect(0, 140, 105, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l3_radioButton_3.setFont(font)
        self.l3_radioButton_3.setObjectName("l3_radioButton_3")
        self.sc_lineEdit_7 = QtWidgets.QLineEdit(self.LevelgroupBox)
        self.sc_lineEdit_7.setGeometry(QtCore.QRect(110, 40, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sc_lineEdit_7.setFont(font)
        self.sc_lineEdit_7.setPlaceholderText("")
        self.sc_lineEdit_7.setObjectName("sc_lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.LevelgroupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 90, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.LevelgroupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 140, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.layoutWidget15 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget15.setGeometry(QtCore.QRect(20, 100, 161, 41))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.layoutWidget16 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget16.setGeometry(QtCore.QRect(20, 148, 291, 41))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget16)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.vaminlabel_8 = QtWidgets.QLabel(self.layoutWidget16)
        self.vaminlabel_8.setObjectName("vaminlabel_8")
        self.horizontalLayout_6.addWidget(self.vaminlabel_8)
        self.vamindoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vamindoubleSpinBox_2.setFont(font)
        self.vamindoubleSpinBox_2.setObjectName("vamindoubleSpinBox_2")
        self.horizontalLayout_6.addWidget(self.vamindoubleSpinBox_2)
        self.vamaxlabel_8 = QtWidgets.QLabel(self.layoutWidget16)
        self.vamaxlabel_8.setObjectName("vamaxlabel_8")
        self.horizontalLayout_6.addWidget(self.vamaxlabel_8)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_2)
        self.layoutWidget17 = QtWidgets.QWidget(self.tab_10)
        self.layoutWidget17.setGeometry(QtCore.QRect(20, 200, 291, 61))
        self.layoutWidget17.setObjectName("layoutWidget17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget17)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.originlabel_8 = QtWidgets.QLabel(self.layoutWidget17)
        self.originlabel_8.setObjectName("originlabel_8")
        self.horizontalLayout_7.addWidget(self.originlabel_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget17)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.closeButton_3 = QtWidgets.QPushButton(self.tab_10)
        self.closeButton_3.setGeometry(QtCore.QRect(230, 570, 110, 32))
        self.closeButton_3.setObjectName("closeButton_3")
        self.ImProptabWidget_2.addTab(self.tab_10, "")
        self.MDToolstabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Instruc_overlabel_8 = QtWidgets.QLabel(self.tab_6)
        self.Instruc_overlabel_8.setGeometry(QtCore.QRect(130, 10, 81, 21))
        self.Instruc_overlabel_8.setObjectName("Instruc_overlabel_8")
        self.overplainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_6)
        self.overplainTextEdit_2.setGeometry(QtCore.QRect(60, 30, 241, 41))
        self.overplainTextEdit_2.setReadOnly(True)
        self.overplainTextEdit_2.setObjectName("overplainTextEdit_2")
        self.limgroupBox = QtWidgets.QGroupBox(self.tab_6)
        self.limgroupBox.setGeometry(QtCore.QRect(20, 90, 331, 291))
        self.limgroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.limgroupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.limgroupBox.setObjectName("limgroupBox")
        self.OverlaypushButton_4 = QtWidgets.QPushButton(self.limgroupBox)
        self.OverlaypushButton_4.setGeometry(QtCore.QRect(10, 260, 85, 26))
        self.OverlaypushButton_4.setObjectName("OverlaypushButton_4")
        self.layoutWidget18 = QtWidgets.QWidget(self.limgroupBox)
        self.layoutWidget18.setGeometry(QtCore.QRect(10, 20, 311, 231))
        self.layoutWidget18.setObjectName("layoutWidget18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget18)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.alfalabel_8 = QtWidgets.QLabel(self.layoutWidget18)
        self.alfalabel_8.setObjectName("alfalabel_8")
        self.horizontalLayout_27.addWidget(self.alfalabel_8)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget18)
        self.doubleSpinBox_3.setMaximum(1.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 0.5)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_27.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lowcollabel_9 = QtWidgets.QLabel(self.layoutWidget18)
        self.lowcollabel_9.setObjectName("lowcollabel_9")
        self.horizontalLayout_28.addWidget(self.lowcollabel_9)
        self.chooselow_pushButton_2 = QtWidgets.QPushButton(self.layoutWidget18)
        self.chooselow_pushButton_2.setObjectName("chooselow_pushButton_2")
        self.horizontalLayout_28.addWidget(self.chooselow_pushButton_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lowlim_label_10 = QtWidgets.QLabel(self.layoutWidget18)
        self.lowlim_label_10.setObjectName("lowlim_label_10")
        self.horizontalLayout_29.addWidget(self.lowlim_label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget18)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_29.addWidget(self.lineEdit_7, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.hicollabel_11 = QtWidgets.QLabel(self.layoutWidget18)
        self.hicollabel_11.setObjectName("hicollabel_11")
        self.horizontalLayout_30.addWidget(self.hicollabel_11)
        self.hicolpushButton_3 = QtWidgets.QPushButton(self.layoutWidget18)
        self.hicolpushButton_3.setObjectName("hicolpushButton_3")
        self.horizontalLayout_30.addWidget(self.hicolpushButton_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.hilim_label_12 = QtWidgets.QLabel(self.layoutWidget18)
        self.hilim_label_12.setObjectName("hilim_label_12")
        self.horizontalLayout_31.addWidget(self.hilim_label_12)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget18)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_31.addWidget(self.lineEdit_10, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.closeButton_4 = QtWidgets.QPushButton(self.tab_6)
        self.closeButton_4.setGeometry(QtCore.QRect(240, 700, 110, 32))
        self.closeButton_4.setObjectName("closeButton_4")
        self.ContrastTitle = QtWidgets.QLabel(self.tab_6)
        self.ContrastTitle.setGeometry(QtCore.QRect(140, 440, 91, 31))
        self.ContrastTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.ContrastTitle.setObjectName("ContrastTitle")
        self.layoutWidget19 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget19.setGeometry(QtCore.QRect(21, 481, 331, 74))
        self.layoutWidget19.setObjectName("layoutWidget19")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.layoutWidget19)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.CutLowlabel = QtWidgets.QLabel(self.layoutWidget19)
        self.CutLowlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.CutLowlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CutLowlabel.setObjectName("CutLowlabel")
        self.verticalLayout_14.addWidget(self.CutLowlabel)
        self.numLowlabel = QtWidgets.QLabel(self.layoutWidget19)
        self.numLowlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.numLowlabel.setText("")
        self.numLowlabel.setObjectName("numLowlabel")
        self.verticalLayout_14.addWidget(self.numLowlabel)
        self.horizontalLayout_37.addLayout(self.verticalLayout_14)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalSliderLow = QtWidgets.QSlider(self.layoutWidget19)
        self.horizontalSliderLow.setMinimum(0)
        self.horizontalSliderLow.setMaximum(99)
        self.horizontalSliderLow.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderLow.setInvertedControls(True)
        self.horizontalSliderLow.setObjectName("horizontalSliderLow")
        self.horizontalLayout_22.addWidget(self.horizontalSliderLow)
        self.horizontalSliderHigh = QtWidgets.QSlider(self.layoutWidget19)
        self.horizontalSliderHigh.setProperty("value", 99)
        self.horizontalSliderHigh.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderHigh.setInvertedAppearance(False)
        self.horizontalSliderHigh.setInvertedControls(True)
        self.horizontalSliderHigh.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSliderHigh.setObjectName("horizontalSliderHigh")
        self.horizontalLayout_22.addWidget(self.horizontalSliderHigh)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_22)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.CutHighlabel = QtWidgets.QLabel(self.layoutWidget19)
        self.CutHighlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.CutHighlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CutHighlabel.setObjectName("CutHighlabel")
        self.verticalLayout_15.addWidget(self.CutHighlabel)
        self.numHighlabel = QtWidgets.QLabel(self.layoutWidget19)
        self.numHighlabel.setMinimumSize(QtCore.QSize(0, 31))
        self.numHighlabel.setText("")
        self.numHighlabel.setObjectName("numHighlabel")
        self.verticalLayout_15.addWidget(self.numHighlabel)
        self.horizontalLayout_37.addLayout(self.verticalLayout_15)
        self.MDToolstabWidget_2.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(60, 30, 231, 61))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.start_lassoButton = QtWidgets.QPushButton(self.tab)
        self.start_lassoButton.setGeometry(QtCore.QRect(50, 110, 110, 32))
        self.start_lassoButton.setObjectName("start_lassoButton")
        self.stop_lassoButton = QtWidgets.QPushButton(self.tab)
        self.stop_lassoButton.setGeometry(QtCore.QRect(190, 110, 110, 32))
        self.stop_lassoButton.setObjectName("stop_lassoButton")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(150, 230, 56, 13))
        self.label_8.setObjectName("label_8")
        self.statisticsplainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.statisticsplainTextEdit.setGeometry(QtCore.QRect(60, 260, 251, 321))
        self.statisticsplainTextEdit.setObjectName("statisticsplainTextEdit")
        self.LassoMaskpushButton = QtWidgets.QPushButton(self.tab)
        self.LassoMaskpushButton.setGeometry(QtCore.QRect(120, 160, 110, 32))
        self.LassoMaskpushButton.setObjectName("LassoMaskpushButton")
        self.closeButton_5 = QtWidgets.QPushButton(self.tab)
        self.closeButton_5.setGeometry(QtCore.QRect(240, 700, 110, 32))
        self.closeButton_5.setObjectName("closeButton_5")
        self.MDToolstabWidget_2.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.instruc_md_label_8 = QtWidgets.QLabel(self.tab_7)
        self.instruc_md_label_8.setGeometry(QtCore.QRect(130, 10, 81, 16))
        self.instruc_md_label_8.setObjectName("instruc_md_label_8")
        self.Instruc_md_plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_7)
        self.Instruc_md_plainTextEdit_2.setGeometry(QtCore.QRect(50, 30, 251, 51))
        self.Instruc_md_plainTextEdit_2.setReadOnly(True)
        self.Instruc_md_plainTextEdit_2.setObjectName("Instruc_md_plainTextEdit_2")
        self.hdu_label_8 = QtWidgets.QLabel(self.tab_7)
        self.hdu_label_8.setGeometry(QtCore.QRect(150, 90, 31, 16))
        self.hdu_label_8.setObjectName("hdu_label_8")
        self.naxis_label_8 = QtWidgets.QLabel(self.tab_7)
        self.naxis_label_8.setGeometry(QtCore.QRect(110, 110, 121, 21))
        self.naxis_label_8.setObjectName("naxis_label_8")
        self.na1_label_8 = QtWidgets.QLabel(self.tab_7)
        self.na1_label_8.setGeometry(QtCore.QRect(10, 150, 58, 15))
        self.na1_label_8.setObjectName("na1_label_8")
        self.na2_label_9 = QtWidgets.QLabel(self.tab_7)
        self.na2_label_9.setGeometry(QtCore.QRect(10, 180, 58, 15))
        self.na2_label_9.setObjectName("na2_label_9")
        self.na3_label_10 = QtWidgets.QLabel(self.tab_7)
        self.na3_label_10.setGeometry(QtCore.QRect(10, 210, 58, 15))
        self.na3_label_10.setObjectName("na3_label_10")
        self.na1_val_label_8 = QtWidgets.QLabel(self.tab_7)
        self.na1_val_label_8.setGeometry(QtCore.QRect(70, 150, 31, 16))
        self.na1_val_label_8.setText("")
        self.na1_val_label_8.setObjectName("na1_val_label_8")
        self.na2_val_label_8 = QtWidgets.QLabel(self.tab_7)
        self.na2_val_label_8.setGeometry(QtCore.QRect(70, 180, 31, 16))
        self.na2_val_label_8.setText("")
        self.na2_val_label_8.setObjectName("na2_val_label_8")
        self.na3_val_label_8 = QtWidgets.QLabel(self.tab_7)
        self.na3_val_label_8.setGeometry(QtCore.QRect(70, 210, 31, 16))
        self.na3_val_label_8.setText("")
        self.na3_val_label_8.setObjectName("na3_val_label_8")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_7)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 205, 131, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(20)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.slice_label_8 = QtWidgets.QLabel(self.tab_7)
        self.slice_label_8.setGeometry(QtCore.QRect(90, 400, 51, 31))
        self.slice_label_8.setObjectName("slice_label_8")
        self.nslice_label_8 = QtWidgets.QLabel(self.tab_7)
        self.nslice_label_8.setGeometry(QtCore.QRect(150, 400, 61, 31))
        self.nslice_label_8.setText("")
        self.nslice_label_8.setObjectName("nslice_label_8")
        self.layoutWidget20 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget20.setGeometry(QtCore.QRect(70, 340, 221, 51))
        self.layoutWidget20.setObjectName("layoutWidget20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget20)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.framelabel_8 = QtWidgets.QLabel(self.layoutWidget20)
        self.framelabel_8.setObjectName("framelabel_8")
        self.horizontalLayout_11.addWidget(self.framelabel_8)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.layoutWidget20)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_4)
        self.layoutWidget21 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget21.setGeometry(QtCore.QRect(40, 240, 271, 76))
        self.layoutWidget21.setObjectName("layoutWidget21")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget21)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.firstpushButton_2 = QtWidgets.QPushButton(self.layoutWidget21)
        self.firstpushButton_2.setObjectName("firstpushButton_2")
        self.horizontalLayout_9.addWidget(self.firstpushButton_2)
        self.prev_pushButton_3 = QtWidgets.QPushButton(self.layoutWidget21)
        self.prev_pushButton_3.setObjectName("prev_pushButton_3")
        self.horizontalLayout_9.addWidget(self.prev_pushButton_3)
        self.stoppushButton_4 = QtWidgets.QPushButton(self.layoutWidget21)
        self.stoppushButton_4.setObjectName("stoppushButton_4")
        self.horizontalLayout_9.addWidget(self.stoppushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.endpushButton_5 = QtWidgets.QPushButton(self.layoutWidget21)
        self.endpushButton_5.setObjectName("endpushButton_5")
        self.horizontalLayout_10.addWidget(self.endpushButton_5)
        self.nextpushButton_6 = QtWidgets.QPushButton(self.layoutWidget21)
        self.nextpushButton_6.setObjectName("nextpushButton_6")
        self.horizontalLayout_10.addWidget(self.nextpushButton_6)
        self.playpushButton_7 = QtWidgets.QPushButton(self.layoutWidget21)
        self.playpushButton_7.setObjectName("playpushButton_7")
        self.horizontalLayout_10.addWidget(self.playpushButton_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.closeButton_6 = QtWidgets.QPushButton(self.tab_7)
        self.closeButton_6.setGeometry(QtCore.QRect(230, 690, 110, 32))
        self.closeButton_6.setObjectName("closeButton_6")
        self.MDToolstabWidget_2.addTab(self.tab_7, "")
        self.zoomgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.zoomgroupBox.setGeometry(QtCore.QRect(20, 610, 241, 81))
        self.zoomgroupBox.setObjectName("zoomgroupBox")
        self.xinf_spinBox = QtWidgets.QSpinBox(self.zoomgroupBox)
        self.xinf_spinBox.setGeometry(QtCore.QRect(70, 20, 47, 24))
        self.xinf_spinBox.setMaximum(10000)
        self.xinf_spinBox.setObjectName("xinf_spinBox")
        self.yinf_spinBox_2 = QtWidgets.QSpinBox(self.zoomgroupBox)
        self.yinf_spinBox_2.setGeometry(QtCore.QRect(70, 50, 47, 24))
        self.yinf_spinBox_2.setMaximum(10000)
        self.yinf_spinBox_2.setObjectName("yinf_spinBox_2")
        self.ysup_spinBox_3 = QtWidgets.QSpinBox(self.zoomgroupBox)
        self.ysup_spinBox_3.setGeometry(QtCore.QRect(190, 50, 47, 24))
        self.ysup_spinBox_3.setMaximum(10000)
        self.ysup_spinBox_3.setObjectName("ysup_spinBox_3")
        self.xsup_spinBox_4 = QtWidgets.QSpinBox(self.zoomgroupBox)
        self.xsup_spinBox_4.setGeometry(QtCore.QRect(190, 20, 47, 24))
        self.xsup_spinBox_4.setMaximum(10000)
        self.xsup_spinBox_4.setObjectName("xsup_spinBox_4")
        self.xinf_label = QtWidgets.QLabel(self.zoomgroupBox)
        self.xinf_label.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.xinf_label.setObjectName("xinf_label")
        self.yinf_label_2 = QtWidgets.QLabel(self.zoomgroupBox)
        self.yinf_label_2.setGeometry(QtCore.QRect(30, 50, 31, 16))
        self.yinf_label_2.setObjectName("yinf_label_2")
        self.xsup_label_3 = QtWidgets.QLabel(self.zoomgroupBox)
        self.xsup_label_3.setGeometry(QtCore.QRect(160, 20, 31, 16))
        self.xsup_label_3.setObjectName("xsup_label_3")
        self.ysup_label_4 = QtWidgets.QLabel(self.zoomgroupBox)
        self.ysup_label_4.setGeometry(QtCore.QRect(160, 50, 31, 16))
        self.ysup_label_4.setObjectName("ysup_label_4")
        self.PlotRegionpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotRegionpushButton.setGeometry(QtCore.QRect(150, 710, 111, 31))
        self.PlotRegionpushButton.setObjectName("PlotRegionpushButton")
        self.ImagetabWidget_2.raise_()
        self.RestorepushButton_2.raise_()
        self.tabWidget.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.layoutWidget.raise_()
        self.Message.raise_()
        self.MDToolstabWidget_2.raise_()
        self.zoomgroupBox.raise_()
        self.PlotRegionpushButton.raise_()
        FlowsMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FlowsMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1421, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOperation = QtWidgets.QMenu(self.menubar)
        self.menuOperation.setObjectName("menuOperation")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        FlowsMainWindow.setMenuBar(self.menubar)
        self.menutoolBar = QtWidgets.QToolBar(FlowsMainWindow)
        self.menutoolBar.setObjectName("menutoolBar")
        FlowsMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.menutoolBar)
        self.actionClose_Image = QtWidgets.QAction(FlowsMainWindow)
        self.actionClose_Image.setObjectName("actionClose_Image")
        self.actionQuit = QtWidgets.QAction(FlowsMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFlows = QtWidgets.QAction(FlowsMainWindow)
        self.actionFlows.setObjectName("actionFlows")
        self.actionHistogram = QtWidgets.QAction(FlowsMainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionDivergences = QtWidgets.QAction(FlowsMainWindow)
        self.actionDivergences.setObjectName("actionDivergences")
        self.actionOverlays = QtWidgets.QAction(FlowsMainWindow)
        self.actionOverlays.setObjectName("actionOverlays")
        self.actionAbot = QtWidgets.QAction(FlowsMainWindow)
        self.actionAbot.setObjectName("actionAbot")
        self.actionDocumentation = QtWidgets.QAction(FlowsMainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSave = QtWidgets.QAction(FlowsMainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLasso = QtWidgets.QAction(FlowsMainWindow)
        self.actionLasso.setObjectName("actionLasso")
        self.actionOpen_Cube = QtWidgets.QAction(FlowsMainWindow)
        self.actionOpen_Cube.setObjectName("actionOpen_Cube")
        self.actionOpen_Context_Image = QtWidgets.QAction(FlowsMainWindow)
        self.actionOpen_Context_Image.setObjectName("actionOpen_Context_Image")
        self.actionMultiDim = QtWidgets.QAction(FlowsMainWindow)
        self.actionMultiDim.setObjectName("actionMultiDim")
        self.actionNothing = QtWidgets.QAction(FlowsMainWindow)
        self.actionNothing.setObjectName("actionNothing")
        self.actionOpenCube = QtWidgets.QAction(FlowsMainWindow)
        self.actionOpenCube.setObjectName("actionOpenCube")
        self.menuFile.addAction(self.actionOpenCube)
        self.menuFile.addAction(self.actionClose_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuOperation.addAction(self.actionFlows)
        self.menuOperation.addAction(self.actionHistogram)
        self.menuOperation.addAction(self.actionDivergences)
        self.menuOperation.addAction(self.actionOverlays)
        self.menuOperation.addAction(self.actionLasso)
        self.menuOperation.addAction(self.actionMultiDim)
        self.menuHelp.addAction(self.actionAbot)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FlowsMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.ImagetabWidget_2.setCurrentIndex(0)
        self.MDToolstabWidget_2.setCurrentIndex(1)
        self.ImProptabWidget_2.setCurrentIndex(2)
        self.horizontalSlider.valueChanged['int'].connect(self.nslice_label_8.setNum)
        self.AmplificatorSlider.valueChanged['int'].connect(self.Amplificatorlabel.setNum)
        self.horizontalSliderLow.sliderMoved['int'].connect(self.numLowlabel.setNum)
        self.horizontalSliderHigh.sliderMoved['int'].connect(self.numHighlabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(FlowsMainWindow)

    def retranslateUi(self, FlowsMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FlowsMainWindow.setWindowTitle(_translate("FlowsMainWindow", "Vector Velocities with Sunpy"))
        self.contextlabel.setText(_translate("FlowsMainWindow", "Context Image"))
        self.InfoplainTextEdit.setPlainText(_translate("FlowsMainWindow", "Name : None\n"
"X : \n"
"Y :\n"
"Value : \n"
"Dimensions : \n"
"Min : \n"
"Max :\n"
"Pixel Size :\n"
"Temporal cadence :\n"
"\n"
""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Infotab), _translate("FlowsMainWindow", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FlowsMainWindow", "Header"))
        self.ImagetabWidget_2.setTabText(self.ImagetabWidget_2.indexOf(self.image), _translate("FlowsMainWindow", "Image"))
        self.axes_label_8.setText(_translate("FlowsMainWindow", "Axes units:"))
        self.arcradioButton.setText(_translate("FlowsMainWindow", "Arcseconds"))
        self.meter_radioButton_2.setText(_translate("FlowsMainWindow", "Mm"))
        self.RestorepushButton_2.setText(_translate("FlowsMainWindow", "Redraw"))
        self.Message.setText(_translate("FlowsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">In this workspace will be open </span></p><p align=\"center\"><span style=\" font-size:24pt;\">the avalaible operations</span></p><p align=\"center\"><br/></p></body></html>"))
        self.Intruc_flowlabel_2.setText(_translate("FlowsMainWindow", "Instructions"))
        self.Instru1plainTextEdit.setPlainText(_translate("FlowsMainWindow", "Enter the different parameters to calculate flow vectors field."))
        self.Options_CalcgroupBox.setTitle(_translate("FlowsMainWindow", "Options to calculate:"))
        self.labelTitle.setText(_translate("FlowsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Values for time average</span></p></body></html>"))
        self.FWHM1_2.setText(_translate("FlowsMainWindow", "FHWM (arcsec per pixel)"))
        self.Pixelsize_2.setText(_translate("FlowsMainWindow", "Pixel size (arcsec)"))
        self.label.setText(_translate("FlowsMainWindow", "Cadence (seconds)"))
        self.labelInit.setText(_translate("FlowsMainWindow", "Initial Image:"))
        self.labelEnd.setText(_translate("FlowsMainWindow", "Last Image:"))
        self.vectorOptiongroupBox.setTitle(_translate("FlowsMainWindow", "Vector Options:"))
        self.Pixel_2.setText(_translate("FlowsMainWindow", "Density of vectors"))
        self.Color_2.setText(_translate("FlowsMainWindow", "Color"))
        self.ColorSelector.setText(_translate("FlowsMainWindow", "Color"))
        self.Pivot_2.setText(_translate("FlowsMainWindow", "Pivot"))
        self.PivotSelector.setItemText(0, _translate("FlowsMainWindow", "tail"))
        self.PivotSelector.setItemText(1, _translate("FlowsMainWindow", "middle"))
        self.PivotSelector.setItemText(2, _translate("FlowsMainWindow", "tip"))
        self.Width_2.setText(_translate("FlowsMainWindow", "Width"))
        self.Scale_2.setText(_translate("FlowsMainWindow", "Scale"))
        self.Units_2.setText(_translate("FlowsMainWindow", "Units"))
        self.UnitsSelector.setItemText(0, _translate("FlowsMainWindow", "dots"))
        self.UnitsSelector.setItemText(1, _translate("FlowsMainWindow", "inches"))
        self.maskPushButton.setText(_translate("FlowsMainWindow", "Mask"))
        self.fullImageButton.setText(_translate("FlowsMainWindow", "Full Image"))
        self.pushButton.setText(_translate("FlowsMainWindow", "Calculate"))
        self.vmasklabel.setText(_translate("FlowsMainWindow", "Velocity Mask"))
        self.masklabel.setText(_translate("FlowsMainWindow", "Intensity Mask"))
        self.vminlabel_5.setText(_translate("FlowsMainWindow", "Vmin"))
        self.vmaxlabel_6.setText(_translate("FlowsMainWindow", "Vmax"))
        self.iminlabel_7.setText(_translate("FlowsMainWindow", "Imin"))
        self.imaxlabel_8.setText(_translate("FlowsMainWindow", "Imax"))
        self.closeButton_1.setText(_translate("FlowsMainWindow", "Close"))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_3), _translate("FlowsMainWindow", "Flows Tools"))
        self.SaveHist_pushButton.setText(_translate("FlowsMainWindow", "Save Histogram"))
        self.closeButton_2.setText(_translate("FlowsMainWindow", "Close"))
        self.Intruc_histolabel_2.setText(_translate("FlowsMainWindow", "Instructions"))
        self.histo_plainTextEdit.setPlainText(_translate("FlowsMainWindow", "Draw (or redraw) a region with the left mouse button. Or you can chose some parameter to calculate the histogram."))
        self.RegionpushButton_2.setText(_translate("FlowsMainWindow", "Region"))
        self.fullhistpushButton.setText(_translate("FlowsMainWindow", "Full Image"))
        self.pixelradioButton.setText(_translate("FlowsMainWindow", "Pixel distribution"))
        self.velocityradioButton_2.setText(_translate("FlowsMainWindow", "Velocity distribution"))
        self.checkBoxFit.setText(_translate("FlowsMainWindow", "Plot Fit"))
        self.LOGcheckBox.setText(_translate("FlowsMainWindow", "Log Histogram"))
        self.propertiesButton.setText(_translate("FlowsMainWindow", "Plot Tools"))
        self.fitButton.setText(_translate("FlowsMainWindow", "Fit functions \n"
"Properties"))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_4), _translate("FlowsMainWindow", "Histogram Tools"))
        self.diverlabel_5.setText(_translate("FlowsMainWindow", "Instructions"))
        self.plainTextEdit.setPlainText(_translate("FlowsMainWindow", "Plot the divergences map. You can choose overplot with vectors or contours."))
        self.cmaptoolButton.setText(_translate("FlowsMainWindow", "CMAP"))
        self.label_5.setText(_translate("FlowsMainWindow", "Contrast Low:"))
        self.label_6.setText(_translate("FlowsMainWindow", "Contrast High"))
        self.vecradioButton.setText(_translate("FlowsMainWindow", "Vectors"))
        self.contourradioButton.setText(_translate("FlowsMainWindow", "Contours"))
        self.plot_diverpushButton.setText(_translate("FlowsMainWindow", "Plot"))
        self.AmpliTitleLabel.setText(_translate("FlowsMainWindow", "Amplificator"))
        self.Amplificatorlabel.setText(_translate("FlowsMainWindow", "1"))
        self.alphaTitleLabel.setText(_translate("FlowsMainWindow", "Opacity"))
        self.alphalineEdit.setText(_translate("FlowsMainWindow", "1.0"))
        self.ImProptabWidget_2.setTabText(self.ImProptabWidget_2.indexOf(self.tab_8), _translate("FlowsMainWindow", "Image Properties"))
        self.Pixel_4.setText(_translate("FlowsMainWindow", "Density of vectors"))
        self.Color_4.setText(_translate("FlowsMainWindow", "Color"))
        self.ColorSelector_2.setText(_translate("FlowsMainWindow", "Color"))
        self.Pivot_4.setText(_translate("FlowsMainWindow", "Pivot"))
        self.PivotSelector_2.setItemText(0, _translate("FlowsMainWindow", "tail"))
        self.PivotSelector_2.setItemText(1, _translate("FlowsMainWindow", "middle"))
        self.PivotSelector_2.setItemText(2, _translate("FlowsMainWindow", "tip"))
        self.Width_4.setText(_translate("FlowsMainWindow", "Width"))
        self.Scale_4.setText(_translate("FlowsMainWindow", "Scale"))
        self.Units_4.setText(_translate("FlowsMainWindow", "Units"))
        self.UnitsSelector_2.setItemText(0, _translate("FlowsMainWindow", "dots"))
        self.UnitsSelector_2.setItemText(1, _translate("FlowsMainWindow", "inches"))
        self.ImProptabWidget_2.setTabText(self.ImProptabWidget_2.indexOf(self.tab_9), _translate("FlowsMainWindow", "Vector Properties"))
        self.CMAP_contourtoolButton.setText(_translate("FlowsMainWindow", "CMAP"))
        self.LevelgroupBox.setTitle(_translate("FlowsMainWindow", "Levels"))
        self.l1_radioButton.setText(_translate("FlowsMainWindow", "Single Value"))
        self.l2_radioButton_2.setText(_translate("FlowsMainWindow", "List Values"))
        self.l3_radioButton_3.setText(_translate("FlowsMainWindow", "Range Values"))
        self.sc_lineEdit_7.setText(_translate("FlowsMainWindow", "10"))
        self.lineEdit_8.setPlaceholderText(_translate("FlowsMainWindow", "e. g. 10,13,16,.."))
        self.lineEdit_9.setPlaceholderText(_translate("FlowsMainWindow", "e. g. start,end, npartitions"))
        self.label_7.setText(_translate("FlowsMainWindow", "Alpha"))
        self.vaminlabel_8.setText(_translate("FlowsMainWindow", "Value Min"))
        self.vamaxlabel_8.setText(_translate("FlowsMainWindow", "Value Max"))
        self.originlabel_8.setText(_translate("FlowsMainWindow", "Origin"))
        self.lineEdit_6.setPlaceholderText(_translate("FlowsMainWindow", "None | upper | lower | image"))
        self.closeButton_3.setText(_translate("FlowsMainWindow", "Close"))
        self.ImProptabWidget_2.setTabText(self.ImProptabWidget_2.indexOf(self.tab_10), _translate("FlowsMainWindow", "Countours Properties"))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_5), _translate("FlowsMainWindow", "Divergences Tools"))
        self.Instruc_overlabel_8.setText(_translate("FlowsMainWindow", "Instructions"))
        self.overplainTextEdit_2.setPlainText(_translate("FlowsMainWindow", "Enter the limits for saturation."))
        self.limgroupBox.setTitle(_translate("FlowsMainWindow", "Overlay"))
        self.OverlaypushButton_4.setText(_translate("FlowsMainWindow", "Overlay"))
        self.alfalabel_8.setText(_translate("FlowsMainWindow", "alpha"))
        self.lowcollabel_9.setText(_translate("FlowsMainWindow", "Low Color"))
        self.chooselow_pushButton_2.setText(_translate("FlowsMainWindow", "Choose Color"))
        self.lowlim_label_10.setText(_translate("FlowsMainWindow", "Low Limit"))
        self.hicollabel_11.setText(_translate("FlowsMainWindow", "High Color"))
        self.hicolpushButton_3.setText(_translate("FlowsMainWindow", "Choose Color"))
        self.hilim_label_12.setText(_translate("FlowsMainWindow", "High Limit"))
        self.closeButton_4.setText(_translate("FlowsMainWindow", "Close"))
        self.ContrastTitle.setText(_translate("FlowsMainWindow", "Contrast Tool"))
        self.CutLowlabel.setText(_translate("FlowsMainWindow", "Cut Low"))
        self.CutHighlabel.setText(_translate("FlowsMainWindow", "Cut High"))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_6), _translate("FlowsMainWindow", "Overlays Tools"))
        self.plainTextEdit_2.setPlainText(_translate("FlowsMainWindow", "With this option you can select ans specific mask and erase vectors of selected region."))
        self.start_lassoButton.setText(_translate("FlowsMainWindow", "Start"))
        self.stop_lassoButton.setText(_translate("FlowsMainWindow", "Stop"))
        self.label_8.setText(_translate("FlowsMainWindow", "Statistics"))
        self.LassoMaskpushButton.setText(_translate("FlowsMainWindow", "Make Mask"))
        self.closeButton_5.setText(_translate("FlowsMainWindow", "Close"))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab), _translate("FlowsMainWindow", "Lasso"))
        self.instruc_md_label_8.setText(_translate("FlowsMainWindow", "Instructions"))
        self.Instruc_md_plainTextEdit_2.setPlainText(_translate("FlowsMainWindow", "Use control buttons to move through the movie. (Cube Data)"))
        self.hdu_label_8.setText(_translate("FlowsMainWindow", "HDU"))
        self.naxis_label_8.setText(_translate("FlowsMainWindow", "NAXIS (Data Cube)"))
        self.na1_label_8.setText(_translate("FlowsMainWindow", "NAXIS 1"))
        self.na2_label_9.setText(_translate("FlowsMainWindow", "NAXIS 2"))
        self.na3_label_10.setText(_translate("FlowsMainWindow", "NAXIS 3"))
        self.slice_label_8.setText(_translate("FlowsMainWindow", "Slice:"))
        self.framelabel_8.setText(_translate("FlowsMainWindow", "Num. Frames/sec:"))
        self.firstpushButton_2.setText(_translate("FlowsMainWindow", "First"))
        self.prev_pushButton_3.setText(_translate("FlowsMainWindow", "Previous"))
        self.stoppushButton_4.setText(_translate("FlowsMainWindow", "Stop"))
        self.endpushButton_5.setText(_translate("FlowsMainWindow", "End"))
        self.nextpushButton_6.setText(_translate("FlowsMainWindow", "Next"))
        self.playpushButton_7.setText(_translate("FlowsMainWindow", "Play"))
        self.closeButton_6.setText(_translate("FlowsMainWindow", "Close"))
        self.MDToolstabWidget_2.setTabText(self.MDToolstabWidget_2.indexOf(self.tab_7), _translate("FlowsMainWindow", "MultiDim"))
        self.zoomgroupBox.setTitle(_translate("FlowsMainWindow", "Zooming region"))
        self.xinf_label.setText(_translate("FlowsMainWindow", "xinf"))
        self.yinf_label_2.setText(_translate("FlowsMainWindow", "yinf"))
        self.xsup_label_3.setText(_translate("FlowsMainWindow", "xsup"))
        self.ysup_label_4.setText(_translate("FlowsMainWindow", "ysup"))
        self.PlotRegionpushButton.setText(_translate("FlowsMainWindow", "Resize Window"))
        self.menuFile.setTitle(_translate("FlowsMainWindow", "File"))
        self.menuOperation.setTitle(_translate("FlowsMainWindow", "Operation"))
        self.menuHelp.setTitle(_translate("FlowsMainWindow", "Help"))
        self.menutoolBar.setWindowTitle(_translate("FlowsMainWindow", "toolBar"))
        self.actionClose_Image.setText(_translate("FlowsMainWindow", "Close"))
        self.actionQuit.setText(_translate("FlowsMainWindow", "Quit"))
        self.actionFlows.setText(_translate("FlowsMainWindow", "Flows"))
        self.actionHistogram.setText(_translate("FlowsMainWindow", "Histogram"))
        self.actionDivergences.setText(_translate("FlowsMainWindow", "Divergences"))
        self.actionOverlays.setText(_translate("FlowsMainWindow", "Overlays"))
        self.actionAbot.setText(_translate("FlowsMainWindow", "Abot"))
        self.actionDocumentation.setText(_translate("FlowsMainWindow", "Documentation"))
        self.actionSave.setText(_translate("FlowsMainWindow", "Save"))
        self.actionLasso.setText(_translate("FlowsMainWindow", "Lasso"))
        self.actionOpen_Cube.setText(_translate("FlowsMainWindow", "Open Cube"))
        self.actionOpen_Context_Image.setText(_translate("FlowsMainWindow", "Open Context Image"))
        self.actionMultiDim.setText(_translate("FlowsMainWindow", "MultiDim"))
        self.actionNothing.setText(_translate("FlowsMainWindow", "Nothing"))
        self.actionOpenCube.setText(_translate("FlowsMainWindow", "Open Cube"))

